import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import rules from '../scripts/recipe-rules.js';
import {loadRuntimeIntegrationEngine} from './helpers/runtime-catalog-loader.mjs';
const root=new URL('../',import.meta.url),plain=x=>JSON.parse(JSON.stringify(x));
const fileFetch=async url=>{const bytes=fs.readFileSync(new URL(String(url).replace(/^\.\//,''),root));return {ok:true,status:200,text:async()=>bytes.toString('utf8'),json:async()=>JSON.parse(bytes)};};
async function world(){const e=loadRuntimeIntegrationEngine(root,{fetch:fileFetch});e.setState({items:e.catalogs.items});await e.itemsApi.load();await e.recipesApi.load();e.abilitiesApi.quiet();return e;}
function fixture(e,recipe){const actor=e.buildBlank();actor.id='artisan';actor.name='Мастер';actor.hp=20;actor.inventory=[];actor.equipment={};actor.knownRecipes=[recipe.id];actor.craftingFacilities=[];actor.toolProficiencies=[];actor.cls=recipe.requirements.ritualCaster?'Жрец':'Воин';actor.slots={1:{cur:2,max:2}};const choices={inputs:{},entries:{},stations:[],facilities:[],minutes:10,resultId:recipe.resultIds[0]},counts=new Map();
recipe.inputs.forEach((input,index)=>{if(input.station){choices.stations.push(index);return;}const id=input.ids[0];choices.inputs[index]=id;counts.set(id,(counts.get(id)||0)+input.qty);});
for(const id of recipe.toolIds){counts.set(id,Math.max(1,counts.get(id)||0));const tool=e.itemProfile(e.itemsApi.resolve(id)).tool;if(tool)actor.toolProficiencies.push(tool.prof);}
actor.craftingFacilities=e.recipesApi.requirements(recipe.raw).facilities||[];choices.facilities=actor.craftingFacilities.slice();
for(const [itemId,qty] of counts)actor.inventory.push({id:'component-'+actor.inventory.length,itemId,qty});recipe.inputs.forEach((input,index)=>{if(['Dye','Transform'].includes(input.operation))choices.entries[index]=actor.inventory.find(x=>x.itemId===choices.inputs[index]).id;});return {actor,choices};}
test('all 265 source records have an explicit disposition and every genuine recipe has complete presentation',async()=>{const e=await world(),asset=await e.recipesApi.load(),recipes=e.recipesApi.rows();assert.equal(asset.recipes.length+e.recipesApi.local.length,265);assert.equal(recipes.length,200);assert.equal(recipes.filter(r=>r.source!=='game').length,0);for(const r of recipes){assert.ok(r.name&&r.description&&r.iconItem,r.id);assert.ok(r.inputs.every(i=>i.label&&i.ids.length&&i.qty>0),r.id);assert.ok(r.dye||r.resultIds.length,r.id);assert.doesNotMatch(r.name,/Готовый предмет|^Объект$|Тахта с обивкой/,r.id);assert.match(e.itemsApi.icon(r.iconItem,40),/<img/,r.id);}const dyes=recipes.filter(r=>r.dye);assert.equal(dyes.length,42);assert.equal(new Set(dyes.map(r=>r.name)).size,42);assert.ok(dyes.every(r=>!r.name.includes('Шепчущая маска')));const groups=e.recipesApi.groups();assert.equal(new Set(groups.map(g=>g.name)).size,groups.length);assert.ok(groups.find(g=>g.name==='Противоядие').methods.length>1);const extract=recipes.find(r=>r.id.endsWith(':ALCH_Extract_FireAmber'));assert.equal(extract.inputs.length,1);assert.equal(extract.inputs[0].qty,3);const potion=recipes.find(r=>r.id.endsWith(':ALCH_Potion_Healing_RoguesMorsel'));assert.ok(potion.inputs.some(i=>i.label==='Любая суспензия'));});
test('the pure planner reserves overlapping pools and never spends a reusable ingredient',()=>{const recipe={id:'r',inputs:[{ids:['salt'],qty:2,label:'Соль',operation:'Consume'},{ids:['salt','ash'],qty:1,label:'Катализатор',operation:'None',category:'any'}],resultIds:['out'],resultQty:1},actor={inventory:[{id:'salt',itemId:'salt',qty:2}],equipment:{}};assert.equal(rules.plan(recipe,actor,{inputs:{1:'salt'}}).ok,false);actor.inventory[0].qty=3;const plan=rules.plan(recipe,actor,{inputs:{1:'salt'}});assert.equal(plan.ok,true);assert.equal(plan.deductions.reduce((n,d)=>n+d.qty,0),2);assert.equal(actor.inventory[0].qty,3);});
test('default ingredient choices reserve exact components and recipe duration can return to an explicit master choice',async()=>{
 const e=await world(),recipe={id:'r',inputs:[{ids:['salt'],qty:2,label:'Соль',operation:'Consume'},{ids:['salt','ash'],qty:1,label:'Катализатор',operation:'None',category:'any'}],resultIds:['out'],resultQty:1},actor={inventory:[{id:'salt',itemId:'salt',qty:2},{id:'ash',itemId:'ash',qty:1}],equipment:{}};
 const choices=e.recipesApi.defaults(recipe,actor);assert.equal(choices.inputs[1],'ash');assert.equal(rules.plan(recipe,actor,choices).ok,true);
 e.recipesApi.setState({overrides:{cr_iron_ingot:{name:'Железный слиток',minutes:null}}});assert.equal(e.recipesApi.of('cr_iron_ingot').durationMinutes,null);
});
test('a retained compatibility plan also cannot manufacture twice from one confirmation',async()=>{
 const e=await world(),r=e.recipesApi.of('cr_iron_ingot'),{actor}=fixture(e,r);for(const entry of actor.inventory)if(!r.toolIds.includes(entry.itemId))entry.qty*=2;e.setState({items:e.catalogs.items,chars:[actor]});const plan=e.recipesApi.legacyPlan(actor,r.id);assert.equal(plan.ok,true,plan.reason);assert.equal(e.recipesApi.legacyCommit(plan).ok,true);assert.equal(e.recipesApi.legacyCommit(plan).ok,false);assert.equal(e.inventoryItemQty(actor,r.resultIds[0]),1);
});
test('every displayed recipe executes through the shared engine exactly once',async t=>{const e=await world();for(const recipe of e.recipesApi.rows())await t.test(recipe.id,async()=>{const {actor,choices}=fixture(e,recipe);e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const before=plain(actor.inventory),round=e.state().fxRound;const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.deepEqual(plain(actor.inventory),before,'preflight does not mutate');const done=await e.recipesApi.commitGame(prepared);assert.equal(done.ok,true,done.reason);assert.equal(e.state().fxRound,round+prepared.minutes*10);assert.equal(actor.craftingLog.length,1);for(const input of recipe.inputs.filter(i=>i.operation==='Consume')){const consumed=input.ids.reduce((n,id)=>n+before.filter(x=>x.itemId===id).reduce((a,x)=>a+x.qty,0)-e.inventoryItemQty(actor,id),0);assert.ok(consumed>=input.qty,recipe.id+' consumes '+input.label);}for(const id of recipe.toolIds)assert.ok(e.inventoryItemQty(actor,id)>=1,'tool survives');if(recipe.requirements.ritualCaster)assert.equal(actor.slots[1].cur,1);if(recipe.dye)assert.equal(actor.inventory.length,1);else assert.ok(e.inventoryItemQty(actor,choices.resultId)>=recipe.resultQty);const committed=JSON.stringify(e.state().chars);assert.equal((await e.recipesApi.commitGame(prepared)).ok,false);assert.equal(JSON.stringify(e.state().chars),committed);});});
test('stale plans, missing knowledge and combat reject without spending anything',async()=>{const e=await world(),r=e.recipesApi.of('cr_iron_ingot'),{actor,choices}=fixture(e,r);e.setState({items:e.catalogs.items,chars:[actor]});const plan=await e.recipesApi.prepare(r.id,actor.id,choices);assert.equal(plan.ok,true,plan.reason);actor.inventory.find(x=>x.itemId==='it_mat_coal').qty=0;const before=JSON.stringify(e.state().chars);assert.equal((await e.recipesApi.commitGame(plan)).ok,false);assert.equal(JSON.stringify(e.state().chars),before);actor.inventory.find(x=>x.itemId==='it_mat_coal').qty=1;e.state().combat.active=true;assert.equal((await e.recipesApi.prepare(r.id,actor.id,choices)).ok,false);e.state().combat.active=false;const potion=e.recipesApi.of('cr_potion_flying');const f=fixture(e,potion);f.actor.knownRecipes=[];e.setState({items:e.catalogs.items,chars:[f.actor]});assert.match((await e.recipesApi.prepare(potion.id,f.actor.id,f.choices)).reason,/формулу/);});
test('a failed durable save restores inventory, spell slots, history and elapsed world time',async()=>{const e=await world(),r=e.recipesApi.of('cr_holy_water'),{actor,choices}=fixture(e,r);e.setState({items:e.catalogs.items,chars:[actor]});const plan=await e.recipesApi.prepare(r.id,actor.id,choices);assert.equal(plan.ok,true,plan.reason);const before=JSON.stringify(e.state().chars),round=e.state().fxRound;e.recipesApi.failPersistence();const done=await e.recipesApi.commitGame(plan);assert.equal(done.ok,false);assert.equal(JSON.stringify(e.state().chars),before);assert.equal(e.state().fxRound,round);});
test('recipe notes, names and time survive the same export/import contract as the world',async()=>{const e=await world();e.recipesApi.setState({favorites:['cr_iron_ingot'],overrides:{cr_iron_ingot:{name:'Слиток нашей кузницы',note:'Запись мастера',minutes:180}}});const payload=plain(e.itemsApi.export()),restored=await world();restored.setState(payload);const recipe=restored.recipesApi.of('cr_iron_ingot');assert.equal(recipe.name,'Слиток нашей кузницы');assert.equal(recipe.note,'Запись мастера');assert.equal(recipe.durationMinutes,180);assert.equal(recipe.favorite,true);});
test('coloring accepts native game armor and preserves the exact equipped instance',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.dye?.presetResource),{actor,choices}=fixture(e,recipe),index=recipe.inputs.findIndex(i=>i.operation==='Dye');
 assert.ok(recipe.inputs[index].ids.includes('it_holy_shield_life'));
 const target=actor.inventory.find(x=>x.id===choices.entries[index]);Object.assign(target,{itemId:'it_holy_shield_life',notes:'Дар наставника',att:true,charges:2});choices.inputs[index]=target.itemId;
 const unrelated={id:'another-shield',itemId:target.itemId,qty:1,notes:'Другой щит'};actor.inventory.push(unrelated);actor.equipment.OFF_HAND=target.id;
 e.setState({items:e.catalogs.items,chars:[actor]});const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);const done=await e.recipesApi.commitGame(prepared);assert.equal(done.ok,true,done.reason);
 assert.equal(actor.inventory.find(x=>x.id===target.id),target);assert.equal(actor.inventory.find(x=>x.id===unrelated.id),unrelated);assert.equal(target.notes,'Дар наставника');assert.equal(target.charges,2);assert.equal(target.att,true);assert.equal(actor.equipment.OFF_HAND,target.id);assert.equal(target.bg3Dye.recipeId,recipe.id);assert.equal(unrelated.bg3Dye,undefined);
});
test('transforming a stack preserves its remainder and does not merge a crafted result into a special instance',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.inputs.some(i=>i.operation==='Transform')),{actor,choices}=fixture(e,recipe),index=recipe.inputs.findIndex(i=>i.operation==='Transform'),target=actor.inventory.find(x=>x.id===choices.entries[index]);target.qty=3;target.notes='Отмеченная основа';
 const originalId=target.itemId;e.setState({items:e.catalogs.items,chars:[actor]});const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);assert.equal(target.itemId,choices.resultId);assert.equal(target.qty,1);assert.equal(target.notes,'Отмеченная основа');assert.equal(actor.inventory.find(x=>x.id!==target.id&&x.itemId===originalId).qty,2);
 const ingot=e.recipesApi.of('cr_iron_ingot'),f=fixture(e,ingot),special={id:'special-ingot',itemId:ingot.resultIds[0],qty:1,notes:'Наследие',inside:'chest',charges:3};f.actor.inventory.push(special);e.setState({items:e.catalogs.items,chars:[f.actor]});const plan=await e.recipesApi.prepare(ingot.id,f.actor.id,f.choices);assert.equal(plan.ok,true,plan.reason);assert.equal((await e.recipesApi.commitGame(plan)).ok,true);assert.equal(special.qty,1);assert.equal(f.actor.inventory.filter(x=>x.itemId===special.itemId).length,2);
});
test('clones, concurrent confirmations, missing duration and failed station checks cannot spend twice',async()=>{
 const e=await world(),recipe=e.recipesApi.of('cr_iron_ingot'),{actor,choices}=fixture(e,recipe);for(const entry of actor.inventory)if(!recipe.toolIds.includes(entry.itemId))entry.qty*=2;e.setState({items:e.catalogs.items,chars:[actor]});
 const handle=await e.recipesApi.prepare(recipe.id,actor.id,choices),other=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(handle.ok,true,handle.reason);assert.equal((await e.recipesApi.commitGame({...handle})).ok,false);
 const results=await Promise.all([e.recipesApi.commitGame(handle),e.recipesApi.commitGame(handle),e.recipesApi.commitGame(other)]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(actor.craftingLog.length,1);assert.equal(e.inventoryItemQty(actor,recipe.resultIds[0]),1);
 const station=e.recipesApi.rows().find(r=>r.inputs.some(i=>i.station)),f=fixture(e,station);e.setState({items:e.catalogs.items,chars:[f.actor]});const before=JSON.stringify(e.state().chars);f.choices.stations=[];assert.match((await e.recipesApi.prepare(station.id,f.actor.id,f.choices)).reason,/место работы/);f.choices.stations=station.inputs.map((_,i)=>i);delete f.choices.minutes;assert.match((await e.recipesApi.prepare(station.id,f.actor.id,f.choices)).reason,/длительность/);assert.equal(JSON.stringify(e.state().chars),before);
});

test('renaming an alternative method never splits one result into duplicate cards',()=>{const original=[{id:'a',name:'Зелье лечения',category:'alchemy'},{id:'b',name:'Зелье исцеления',category:'alchemy'}],state=rules.state({overrides:{b:{name:'Формула нашей мастерской'}}}),groups=rules.groups(original.map(r=>rules.applyState(r,state)));assert.equal(groups.length,1);assert.equal(groups[0].methods.length,2);assert.equal(groups[0].methods[1].name,'Формула нашей мастерской');});
test('renaming the shared result preserves its recipe card and unrelated same-name items stay separate',async()=>{
 const e=await world(),before=e.recipesApi.groups(),sourceId='bg3:recipe:ALCH_Potion_Invisibility_ImpPatagium',groupId=before.find(g=>g.methods.some(r=>r.id===sourceId)).id,item=e.itemsApi.resolve('it_potion_invisibility');item.n='Невидимость нашей мастерской';
 assert.equal(e.recipesApi.of(sourceId).name,'Невидимость нашей мастерской');const groups=e.recipesApi.groups(),shared=groups.find(g=>g.id===groupId);assert.equal(groups.length,before.length);assert.deepEqual(plain(shared.methods.map(r=>r.id)).sort(),['cr_potion_invisibility',sourceId].sort());
 const namesakes=rules.groups([{id:'a',name:'Зелье',resultIds:['one']},{id:'b',name:'Зелье',resultIds:['two']}]);assert.equal(namesakes.length,2,'a name match alone cannot merge different game items');
});
test('all five alternative formulas manufacture and use the same tabletop item',async t=>{
 const e=await world(),pairs=[['ALCH_Potion_HealingSuperior_YellowMuskCreeper','cr_potion_superior','it_potion_healing_superior'],['ALCH_Potion_HealingSupreme_KiRinHair','cr_potion_supreme','it_potion_healing_supreme'],['ALCH_Potion_Invisibility_ImpPatagium','cr_potion_invisibility','it_potion_invisibility'],['ALCH_Potion_Flying_EagleFeather','cr_potion_flying','it_potion_flying'],['ALCH_Potion_Antidote_Mugwort','cr_antitoxin','it_противоядие']];
 for(const [sourceId,nativeId,resultId] of pairs)await t.test(sourceId,async()=>{
  const source=e.recipesApi.of('bg3:recipe:'+sourceId),native=e.recipesApi.of(nativeId),raw=JSON.stringify(source.raw),{actor,choices}=fixture(e,source);
  assert.deepEqual(plain(source.resultIds),[resultId]);assert.deepEqual(plain(source.resultIds),plain(native.resultIds));assert.equal(source.iconItem.id,native.iconItem.id);assert.equal(e.recipesApi.groups().find(g=>g.methods.some(r=>r.id===source.id)).methods.length,2);
  e.setState({items:e.catalogs.items,chars:[actor]});const before=JSON.stringify(actor.inventory),prepared=await e.recipesApi.prepare(source.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.equal(prepared.outputStatus.state,'ready');assert.equal(JSON.stringify(actor.inventory),before);
  assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);assert.equal(e.inventoryItemQty(actor,resultId),1);assert.ok(source.raw.result.candidateIds.every(id=>e.inventoryItemQty(actor,id)===0));assert.ok(source.inputs.every(i=>e.inventoryItemQty(actor,choices.inputs[source.inputs.indexOf(i)])===0));assert.ok(actor.knownRecipes.includes(source.id));assert.equal(JSON.stringify(source.raw),raw);
  const item=e.itemsApi.resolve(resultId),use=e.itemUseOf(item,'drink'),entry=actor.inventory.find(x=>x.itemId===resultId);assert.equal(use.cost,'action');assert.equal(use.consume.amount,1);
  let outcome=null;if(use.heal){assert.deepEqual(plain(use.heal),resultId==='it_potion_healing_superior'?{cnt:8,sides:4,mod:8}:{cnt:10,sides:4,mod:20});actor.hp=1;const spec=e.itemUseSpecOf(actor,item,use,e.targetInfoOf('ally:'+actor.id),{});outcome=e.resolveOutcome(spec,{heal:use.heal.cnt});assert.equal(outcome.healTotal,use.heal.cnt+use.heal.mod);}else assert.equal(use.duration.rounds,600);
  assert.equal(e.useItemApply(entry.id,actor.id,'ally:'+actor.id,outcome,'drink'),true);assert.equal(e.inventoryItemQty(actor,resultId),0);assert.equal(e.useItemApply(entry.id,actor.id,'ally:'+actor.id,outcome,'drink'),false,'one dose cannot be used twice');
  if(use.heal)assert.ok(actor.hp>1);else{assert.ok(actor.activeFx.some(f=>f.expiresAtRound===e.state().fxRound+600));if(resultId==='it_potion_invisibility'){assert.deepEqual(plain(use.breakOn),['attack','spell']);assert.ok(actor.activeFx.some(f=>f.fx.some(x=>x.stat==='condition'&&x.value==='Невидимый')));}if(resultId==='it_potion_flying')assert.ok(actor.activeFx.some(f=>f.fx.some(x=>x.stat==='speed.fly'&&x.value==='равна скорости ходьбы')));if(resultId==='it_противоядие'){assert.deepEqual(plain(use.requirements.blockedTags),['undead','construct']);assert.equal(e.charactersApi.rollFxEntries(actor,'save.con',['poison']).some(x=>x.mode==='adv'),true);assert.equal(e.charactersApi.rollFxEntries(actor,'save.con').some(x=>x.mode==='adv'),false);}}
 });
});
test('a missing tabletop definition never falls back to a different source result',async()=>{
 const e=await world(),recipe=e.recipesApi.of('bg3:recipe:ALCH_Potion_Invisibility_ImpPatagium'),adapted=rules.imported(recipe.raw,id=>id==='it_potion_invisibility'?null:{id,n:'Исходный предмет'}),{actor,choices}=fixture(e,recipe);assert.deepEqual(adapted.resultIds,['it_potion_invisibility']);assert.equal(rules.plan(adapted,actor,choices).ok,true);assert.equal(rules.plan(adapted,actor,{...choices,resultId:recipe.raw.result.candidateIds[0]}).code,'RESULT_REQUIRED');
});
test('crafted feather fall uses a sealed confirmation, consumes once and protects only until expiry',async()=>{
 const e=await world(),source=e.recipesApi.of('bg3:recipe:ALCH_Potion_FeatherFall_AutumnCrocus'),{actor,choices}=fixture(e,source);e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const before=JSON.stringify(actor.inventory),prepared=await e.recipesApi.prepare(source.id,actor.id,choices);
 assert.equal(prepared.ok,true,prepared.reason);assert.equal(prepared.outputStatus.state,'ready');assert.equal(JSON.stringify(actor.inventory),before);
 assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);const item=e.itemsApi.resolve(choices.resultId),use=e.itemUsesOf(item)[0],entry=actor.inventory.find(row=>row.itemId===item.id),target='ally:'+actor.id;
 assert.equal(e.useItemApply(entry.id,actor.id,target,{},use.id),false,'a fabricated result cannot spend a dose');
 const stock=JSON.stringify(actor.inventory);assert.equal(await e.itemsApi.open(entry.id,actor.id,use.id),true);e.closeCastModal();assert.equal(JSON.stringify(actor.inventory),stock,'opening and cancelling does not consume');
 assert.equal(await e.itemsApi.open(entry.id,actor.id,use.id),true);e.setElementValue('castTarget',target);e.castConfirm();assert.equal(e.castState().ctx.spec.rows.length,0,'no fabricated dice requirement');assert.equal(e.castFormulaConfirm(),true);assert.equal(e.inventoryItemQty(actor,item.id),0);
 assert.equal(e.useItemApply(entry.id,actor.id,target,{},use.id),false,'one dose cannot be replayed');const hp=actor.hp;
 assert.equal(e.itemsApi.fallDamage(3),true);assert.equal(actor.hp,hp);
 e.itemsApi.damage(target,3,'дробящий','Удар',{sourceKind:'weapon'});assert.equal(actor.hp,hp-3,'ordinary damage is unchanged');
 e.abilitiesApi.advanceFxRound(10);assert.equal(e.itemsApi.fallDamage(3),true);assert.equal(actor.hp,hp-6,'fall protection expires after ten rounds');
});
test('a crafted darkvision elixir respects better sight, consumes once and ends on long rest',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.resultIds.some(id=>e.recipesApi.summary(id)?.statsId==='ALCH_Solution_Elixir_Darkvision')),{actor,choices}=fixture(e,recipe);
 actor.activeFx=[{uid:'natural-vision',id:'natural-vision',k:'custom',mechanicsVersion:1,durationKind:'manual',fx:[{stat:'vision.dark',mode:'min',value:24}]}];e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});
 const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);
 const item=e.itemsApi.resolve(choices.resultId),use=e.itemUsesOf(item)[0],entry=actor.inventory.find(row=>row.itemId===item.id);assert.equal(await e.itemsApi.open(entry.id,actor.id,use.id),true);e.setElementValue('castTarget','ally:'+actor.id);e.castConfirm();assert.equal(e.castFormulaConfirm(),true);
 assert.equal(e.inventoryItemQty(actor,item.id),0);assert.ok(e.itemsApi.effects(actor).some(f=>f.stat==='vision.dark'&&f.value===12));assert.equal(Math.max(...e.itemsApi.effects(actor).filter(f=>f.stat==='vision.dark').map(f=>f.value)),24);
 assert.equal(actor.activeFx.find(f=>f.bg3Status==='ALCH_ELIXIR_DARKVISION').durationKind,'longRest');e.charactersApi.longRest();assert.equal(actor.activeFx.some(f=>f.bg3Status==='ALCH_ELIXIR_DARKVISION'),false);assert.ok(actor.activeFx.some(f=>f.uid==='natural-vision'));
});
test('saved stock antitoxin descriptions are corrected without replacing master edits or mechanics',async()=>{
 const e=await world(),item=e.itemsApi.resolve('it_противоядие'),original='Мутноватая настойка на травах и толченом угле в запечатанном флаконе. Выпитая, дает преимущество на спасброски от яда на следующий час. Не снимает уже полученный урон, но останавливает дальнейшее отравление.',uses=JSON.stringify(item.uses);item.desc=original;item.gameDefinition=true;e.itemsApi.upgrade(item);assert.match(e.recipesApi.outputHTML(item.id),/Не снимает отравление/);assert.match(item.desc,/нежить и конструктов/);assert.equal(JSON.stringify(item.uses),uses);
 item.desc='Настойка нашей мастерской';e.itemsApi.upgrade(item);assert.equal(item.desc,'Настойка нашей мастерской');item.custom=true;item.desc=original;e.itemsApi.upgrade(item);assert.equal(item.desc,original);
});

test('crafted accuracy oil follows the coated weapon and expires without leaking to another weapon',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.resultIds.some(id=>e.recipesApi.summary(id)?.statsId==='ALCH_Solution_Oil_AttackBuff')),{actor,choices}=fixture(e,recipe);
 actor.inventory.push({id:'blade',itemId:'it_кинжал',qty:1},{id:'spare',itemId:'it_кинжал',qty:1});actor.equipment={MAIN_HAND:'blade'};
 e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const made=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(made.ok,true,made.reason);assert.equal((await e.recipesApi.commitGame(made)).ok,true);
 const item=e.itemsApi.resolve(choices.resultId),use=e.itemUsesOf(item)[0],entry=actor.inventory.find(x=>x.itemId===item.id),weapon=e.itemsApi.resolve('it_кинжал'),attack=id=>e.weaponSpecOf(actor,weapon,e.targetInfoOf('ally:'+actor.id),{entryId:id}).rows.find(r=>r.key==='atk').mod,base=attack('blade');
 assert.equal(await e.itemsApi.open(entry.id,actor.id,use.id),true);e.setElementValue('castTarget','ally:'+actor.id);e.castConfirm();assert.equal(e.castFormulaConfirm(),true);assert.equal(e.inventoryItemQty(actor,item.id),0);
 assert.equal((await e.itemsApi.prepareActor(actor,'blade','weapon')).ok,true);assert.equal(attack('blade'),base+2);assert.equal(attack('spare'),base);
 actor.equipment.MAIN_HAND='spare';assert.equal((await e.itemsApi.prepareActor(actor,'spare','weapon')).ok,true);assert.equal(attack('spare'),base,'changing weapons does not transfer the coating');
 actor.equipment.MAIN_HAND='blade';assert.equal((await e.itemsApi.prepareActor(actor,'blade','weapon')).ok,true);assert.equal(attack('blade'),base+2);
 e.abilitiesApi.advanceFxRound(10);assert.equal((await e.itemsApi.prepareActor(actor,'blade','weapon')).ok,true);assert.equal(attack('blade'),base);
});

test('crafted wizardsbane oil applies its penalties only after a hit with the coated weapon',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.resultIds.some(id=>e.recipesApi.summary(id)?.statsId==='ALCH_Solution_Oil_Wizardsbane')),{actor,choices}=fixture(e,recipe),target=e.buildBlank();target.id='enemy';target.hp=40;target.hpMax=40;
 actor.inventory.push({id:'blade',itemId:'it_кинжал',qty:1},{id:'spare',itemId:'it_кинжал',qty:1});actor.equipment={MAIN_HAND:'blade'};e.setState({items:e.catalogs.items,chars:[actor,target],activeCharId:actor.id});
 const made=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(made.ok,true,made.reason);assert.equal((await e.recipesApi.commitGame(made)).ok,true);const item=e.itemsApi.resolve(choices.resultId),use=e.itemUsesOf(item)[0],entry=actor.inventory.find(x=>x.itemId===item.id);
 assert.equal(await e.itemsApi.open(entry.id,actor.id,use.id),true);e.setElementValue('castTarget','ally:'+actor.id);e.castConfirm();assert.equal(e.castFormulaConfirm(),true);assert.equal((await e.itemsApi.prepareActor(actor,'blade','weapon')).ok,true);
 const key='ally:'+target.id,strike=(id,natural)=>{e.charactersApi.weaponAttackFx(id,actor.id,'melee');e.setElementValue('castTarget',key);e.castConfirm();assert.ok(e.castState().ctx?.spec,e.elementText('castErr'));e.setElementValue('cf_atk',natural);e.setElementValue('cf_dmg',natural===1?'':2);e.castFormulaConfirm();return e.castState().ctx===null;};
 assert.equal(strike('blade',1),true);assert.equal((target.activeFx||[]).length,0,'a miss never poisons the target');
 assert.equal(strike('blade',15),true);assert.ok(target.activeFx.some(f=>f.bg3Status==='ALCH_OIL_WIZARDSBANE_CONDITION'));
 assert.equal(e.fxSum(target,'spell.dc'),-3);assert.equal(e.fxSum(target,'spell.atk'),-3);assert.ok(e.charactersApi.rollFxEntries(target,'save.concentration').some(f=>f.mode==='dis'));
 e.abilitiesApi.advanceFxRound(2);assert.equal(e.fxSum(target,'spell.dc'),0);assert.equal(e.fxSum(target,'spell.atk'),0);
});

test('sharpness replaces the prior coating, binds both-handed equipment and makes only that weapon magical',async()=>{
 const e=await world(),actor=e.buildBlank();actor.id='smith';actor.hp=20;actor.inventory=[{id:'blade',itemId:'it_кинжал',qty:1},{id:'spare',itemId:'it_кинжал',qty:1}];actor.equipment={TWO_HAND:'blade'};
 e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const weapon=e.itemsApi.resolve('it_кинжал'),formula=id=>e.weaponSpecOf(actor,weapon,e.targetInfoOf('ally:'+actor.id),{entryId:id}),base=formula('blade').rows[0].mod;
 for(const stats of ['ALCH_Solution_Oil_AttackBuff','ALCH_Solution_Oil_DamageAttackBuff']){
  const recipe=e.recipesApi.rows().find(r=>r.resultIds.some(id=>(e.recipesApi.summary(id)?.statsId||e.itemsApi.resolve(id)?.rules?.sourceStats)===stats));await e.itemsApi.hydrate(recipe.resultIds);const item=e.itemsApi.resolve(recipe.resultIds[0]),use=e.itemUsesOf(item)[0];actor.inventory.push({id:'oil',itemId:item.id,qty:1});
  assert.equal(await e.itemsApi.open('oil',actor.id,use.id),true);e.setElementValue('castTarget','ally:'+actor.id);e.castConfirm();assert.equal(e.castFormulaConfirm(),true,e.elementText('castErr'));assert.equal((await e.itemsApi.prepareActor(actor,'blade','weapon')).ok,true);
 }
 assert.equal(actor.activeFx.filter(f=>f.k==='bg3-equipment-status').length,1);const coated=formula('blade'),spare=formula('spare');assert.equal(coated.rows[0].mod,base+1);assert.equal(spare.rows[0].mod,base);
 assert.equal(coated.meta.damageTags.magical,true);assert.equal(spare.meta.damageTags.magical,false);const fixed=Object.fromEntries(coated.rows.filter(r=>r.fixed).map(r=>[r.key,0]));assert.equal(e.resolveOutcome(coated,{...fixed,atk:15,dmg:2}).dmgTotal,e.resolveOutcome(spare,{atk:15,dmg:2}).dmgTotal+1);
 e.abilitiesApi.advanceFxRound(10);assert.equal((await e.itemsApi.prepareActor(actor,'blade','weapon')).ok,true);assert.equal(formula('blade').meta.damageTags.magical,false);assert.equal(formula('blade').rows[0].mod,base);
});

test('crafted sussur weapons resolve their own hit and save before silencing the target',async t=>{
 const e=await world();
 for(const stats of ['FOR_IncompleteMasterwork_SussurDagger','FOR_IncompleteMasterwork_SussurSickle','FOR_IncompleteMasterwork_SussurGreatsword'])await t.test(stats,async()=>{
  const recipe=e.recipesApi.rows().find(r=>r.resultIds.some(id=>(e.recipesApi.summary(id)?.statsId||e.itemsApi.resolve(id)?.rules?.sourceStats)===stats)),{actor,choices}=fixture(e,recipe),target=e.buildBlank();target.id='silence-target';target.hp=100;target.hpMax=100;
  e.setState({items:e.catalogs.items,chars:[actor,target],activeCharId:actor.id});const made=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(made.ok,true,made.reason);assert.equal((await e.recipesApi.commitGame(made)).ok,true);
  const item=e.itemsApi.resolve(choices.resultId),entry=actor.inventory.find(x=>x.itemId===item.id);actor.equipment={MAIN_HAND:entry.id};assert.equal(e.itemProfile(item).weapon.bonus,1);
  const ready=await e.itemsApi.prepareActor(actor,entry.id,'weapon');assert.equal(ready.ok,true,ready.reason);assert.ok(e.tabletopApi.profile(item)?.onHit);
  const strike=(natural,save)=>{e.charactersApi.weaponAttackFx(entry.id,actor.id,'melee');e.setElementValue('castTarget','ally:'+target.id);e.castConfirm();const spec=e.castState().ctx?.spec;assert.ok(spec,e.elementText('castErr'));assert.equal(spec.rows.find(r=>r.key==='recipe_weapon_save').dc,12);assert.equal(spec.rows.find(r=>r.key==='dmg').mod,1);assert.equal(spec.rows.find(r=>r.key==='atk').mod,3);e.setElementValue('cf_atk',natural);e.setElementValue('cf_dmg',natural===1?'':4);e.setElementValue('cf_recipe_weapon_save',save??'');e.castFormulaConfirm();assert.equal(e.castState().ctx,null,e.elementText('castErr'));};
  strike(1);assert.equal((target.activeFx||[]).length,0,'a miss does not apply silence');
  strike(15,20);assert.equal((target.activeFx||[]).length,0,'a successful save does not apply silence');
  strike(15,1);assert.ok(target.activeFx.some(f=>f.recipeHit?.startsWith('FOR_IncompleteMasterwork_Sussur')));assert.ok(e.itemsApi.effects(target).some(f=>f.stat==='casting.verbal'&&f.value===0));assert.equal(e.charactersApi.dmgAfterTraits(target,10,'звук').amount,0);
  e.abilitiesApi.advanceFxRound(2);assert.equal(target.activeFx.some(f=>f.recipeHit?.startsWith('FOR_IncompleteMasterwork_Sussur')),false);assert.equal(e.charactersApi.dmgAfterTraits(target,10,'звук').amount,10);
 });
});

test('the repaired Absolute spear applies blindness through a confirmed hit and Dexterity save',async()=>{
 const e=await world(),recipe=e.recipesApi.of('bg3:recipe:QUEST_FOR_CultistsRepairedSpear'),{actor,choices}=fixture(e,recipe),target=plain(e.catalogs.foes[0]);target.id='blind-target';target.hp=100;target.hpMax=100;target.ac=10;
 e.setState({items:e.catalogs.items,chars:[actor],foes:[target],activeCharId:actor.id});const made=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(made.ok,true,made.reason);assert.equal((await e.recipesApi.commitGame(made)).ok,true);
 const entry=actor.inventory.find(x=>x.itemId===choices.resultId);actor.equipment={MAIN_HAND:entry.id};assert.equal((await e.itemsApi.prepareActor(actor,entry.id,'weapon')).ok,true);
 assert.equal(e.combatStart([{kind:'ally',id:actor.id,nat:20},{kind:'foe',id:target.id,nat:1}],'Проверка копья'),true);
 e.charactersApi.weaponAttackFx(entry.id,actor.id,'melee');e.setElementValue('castTarget','foe:'+target.id);e.castConfirm();assert.equal(e.castState().ctx.spec.rows.find(r=>r.key==='recipe_weapon_save').dc,11);
 e.setElementValue('cf_atk',19);e.setElementValue('cf_dmg',3);e.setElementValue('cf_recipe_weapon_save',1);e.castFormulaConfirm();assert.equal(e.castState().ctx,null,e.elementText('castErr'));assert.ok(target.activeFx.some(f=>f.recipeHit==='FOR_TrueSoul_Spear'));
 e.abilitiesApi.advanceFxRound(2);assert.equal(target.activeFx.some(f=>f.recipeHit==='FOR_TrueSoul_Spear'),false);
});

test('ordinary weapon ingredients use existing game items and accept older inventory identities',async()=>{
 const e=await world();
 for(const [suffix,nativeId] of [['SussurGreatsword','it_двуручный_меч'],['SussurDagger','it_кинжал'],['SussurSickle','it_серп']]){
  const recipe=e.recipesApi.of('bg3:recipe:QUEST_FOR_'+suffix),input=recipe.inputs.find(row=>row.canonicalIds?.includes(nativeId));assert.ok(input,suffix);assert.deepEqual(plain(input.canonicalIds),[nativeId]);assert.ok(input.aliases.length);assert.ok(e.itemsApi.rows().some(row=>row.id===nativeId));
  const {actor,choices}=fixture(e,recipe),index=recipe.inputs.indexOf(input),entry=actor.inventory.find(row=>row.itemId===nativeId),oldId=input.aliases[0];entry.itemId=oldId;choices.inputs[index]=oldId;
  e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);assert.equal(e.inventoryItemQty(actor,oldId),0);assert.equal(e.inventoryItemQty(actor,choices.resultId),1);
 }
});

test('greater healing and the restored ring point to their actual public game definitions',async()=>{
 const e=await world(),potion=e.recipesApi.of('bg3:recipe:ALCH_Potion_HealingGreater_Balsam');assert.deepEqual(plain(potion.resultIds),['it_potion_great_heal']);assert.deepEqual(plain(e.itemUsesOf(e.itemsApi.resolve(potion.resultIds[0]))[0].heal),{cnt:4,sides:4,mod:4});
 const ring=e.recipesApi.of('bg3:recipe:QUEST_WYR_SharranInformer_MagicRing');await e.itemsApi.hydrate(ring.resultIds);const item=e.itemsApi.resolve(ring.resultIds[0]);assert.ok(e.itemsApi.rows().some(row=>row.id===item.id));assert.equal(item.source.semanticAliasOf,null);assert.equal(e.itemsApi.readiness(item).ok,true);assert.equal(e.itemProfile(item).value.gp,40);assert.match(item.desc,/самоцвет/i);
});

test('equivalent construct parts have one recipe identity and older variants remain usable',async()=>{
 const e=await world(),recipe=e.recipesApi.of('bg3:recipe:ALCH_Extract_ConstructPart'),input=recipe.inputs.find(row=>row.category==='ConstructPart');
 assert.equal(input.canonicalIds.length,1);assert.ok(input.aliases.length>=2);assert.ok(e.itemsApi.rows().some(row=>row.id===input.canonicalIds[0]));
 for(const id of input.ids){
  const {actor,choices}=fixture(e,recipe),index=recipe.inputs.indexOf(input),entry=actor.inventory.find(row=>row.itemId===input.canonicalIds[0]);entry.itemId=id;choices.inputs[index]=id;
  e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);assert.equal(e.inventoryItemQty(actor,id),0);assert.equal(e.inventoryItemQty(actor,choices.resultId),1);
 }
});
