import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import rules from '../scripts/recipe-rules.js';
import {loadRuntimeIntegrationEngine} from './helpers/runtime-catalog-loader.mjs';
const root=new URL('../',import.meta.url),plain=x=>JSON.parse(JSON.stringify(x));
const fileFetch=async url=>{const bytes=fs.readFileSync(new URL(String(url).replace(/^\.\//,''),root));return {ok:true,status:200,text:async()=>bytes.toString('utf8'),json:async()=>JSON.parse(bytes)};};
async function world(){const e=loadRuntimeIntegrationEngine(root,{fetch:fileFetch});e.setState({items:e.catalogs.items});await e.itemsApi.load();await e.recipesApi.load();e.abilitiesApi.quiet();return e;}
function fixture(e,recipe){const actor=e.buildBlank();actor.id='artisan';actor.name='Мастер';actor.hp=20;actor.inventory=[];actor.equipment={};actor.knownRecipes=[recipe.id];actor.craftingFacilities=[];actor.toolProficiencies=[];actor.cls=recipe.requirements.ritualCaster?'Жрец':'Воин';actor.slots={1:{cur:2,max:2}};const choices={inputs:{},entries:{},stations:[],facilities:[],minutes:10,resultId:recipe.resultIds[0]},counts=new Map();
recipe.inputs.forEach((input,index)=>{if(input.station){choices.stations.push(index);return;}const id=input.ids[0];choices.inputs[index]=id;counts.set(id,(counts.get(id)||0)+input.qty);});
for(const id of recipe.toolIds){counts.set(id,Math.max(1,counts.get(id)||0));const tool=e.itemProfile(e.itemsApi.resolve(id)).tool;if(tool)actor.toolProficiencies.push(tool.prof);}
actor.craftingFacilities=e.recipesApi.requirements(recipe.raw).facilities||[];choices.facilities=actor.craftingFacilities.slice();
for(const [itemId,qty] of counts)actor.inventory.push({id:'component-'+actor.inventory.length,itemId,qty});recipe.inputs.forEach((input,index)=>{if(['Dye','Transform'].includes(input.operation))choices.entries[index]=actor.inventory.find(x=>x.itemId===choices.inputs[index]).id;});return {actor,choices};}
test('all 265 source records have an explicit disposition and every genuine recipe has complete presentation',async()=>{const e=await world(),asset=await e.recipesApi.load(),recipes=e.recipesApi.rows();assert.equal(asset.recipes.length+e.recipesApi.local.length,265);assert.equal(recipes.length,200);assert.equal(recipes.filter(r=>r.source!=='game').length,0);for(const r of recipes){assert.ok(r.name&&r.description&&r.iconItem,r.id);assert.ok(r.inputs.every(i=>i.label&&i.ids.length&&i.qty>0),r.id);assert.ok(r.dye||r.resultIds.length,r.id);assert.doesNotMatch(r.name,/Готовый предмет|^Объект$|Тахта с обивкой/,r.id);assert.match(e.itemsApi.icon(r.iconItem,40),/<img/,r.id);}const dyes=recipes.filter(r=>r.dye);assert.equal(dyes.length,42);assert.equal(new Set(dyes.map(r=>r.name)).size,42);assert.ok(dyes.every(r=>!r.name.includes('Шепчущая маска')));const groups=e.recipesApi.groups();assert.equal(new Set(groups.map(g=>g.name)).size,groups.length);assert.ok(groups.find(g=>g.name==='Противоядие').methods.length>1);const extract=recipes.find(r=>r.id.endsWith(':ALCH_Extract_FireAmber'));assert.equal(extract.inputs.length,1);assert.equal(extract.inputs[0].qty,3);const potion=recipes.find(r=>r.id.endsWith(':ALCH_Potion_Healing_RoguesMorsel'));assert.ok(potion.inputs.some(i=>i.label==='Любая суспензия'));});
test('the pure planner reserves overlapping pools and never spends a reusable ingredient',()=>{const recipe={id:'r',inputs:[{ids:['salt'],qty:2,label:'Соль',operation:'Consume'},{ids:['salt','ash'],qty:1,label:'Катализатор',operation:'None',category:'any'}],resultIds:['out'],resultQty:1},actor={inventory:[{id:'salt',itemId:'salt',qty:2}],equipment:{}};assert.equal(rules.plan(recipe,actor,{inputs:{1:'salt'}}).ok,false);actor.inventory[0].qty=3;const plan=rules.plan(recipe,actor,{inputs:{1:'salt'}});assert.equal(plan.ok,true);assert.equal(plan.deductions.reduce((n,d)=>n+d.qty,0),2);assert.equal(actor.inventory[0].qty,3);});
test('default ingredient choices reserve exact components and recipe duration can return to an explicit master choice',async()=>{
 const e=await world(),recipe={id:'r',inputs:[{ids:['salt'],qty:2,label:'Соль',operation:'Consume'},{ids:['salt','ash'],qty:1,label:'Катализатор',operation:'None',category:'any'}],resultIds:['out'],resultQty:1},actor={inventory:[{id:'salt',itemId:'salt',qty:2},{id:'ash',itemId:'ash',qty:1}],equipment:{}};
 const choices=e.recipesApi.defaults(recipe,actor);assert.equal(choices.inputs[1],'ash');assert.equal(rules.plan(recipe,actor,choices).ok,true);
 e.recipesApi.setState({overrides:{cr_iron_ingot:{name:'Железный слиток',minutes:null}}});assert.equal(e.recipesApi.of('cr_iron_ingot').durationMinutes,null);
});
test('a retained compatibility plan also cannot manufacture twice from one confirmation',async()=>{
 const e=await world(),r=e.recipesApi.of('cr_iron_ingot'),{actor}=fixture(e,r);for(const entry of actor.inventory)if(!r.toolIds.includes(entry.itemId))entry.qty*=2;e.setState({items:e.catalogs.items,chars:[actor]});const plan=e.recipesApi.legacyPlan(actor,r.id);assert.equal(plan.ok,true,plan.reason);assert.equal(e.recipesApi.legacyCommit(plan).ok,true);assert.equal(e.recipesApi.legacyCommit(plan).ok,false);assert.equal(e.inventoryItemQty(actor,r.resultIds[0]),1);
});
test('every displayed recipe executes through the shared engine exactly once',async t=>{const e=await world();for(const recipe of e.recipesApi.rows())await t.test(recipe.id,async()=>{const {actor,choices}=fixture(e,recipe);e.setState({items:e.catalogs.items,chars:[actor],activeCharId:actor.id});const before=plain(actor.inventory),round=e.state().fxRound;const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.deepEqual(plain(actor.inventory),before,'preflight does not mutate');const done=await e.recipesApi.commitGame(prepared);assert.equal(done.ok,true,done.reason);assert.equal(e.state().fxRound,round+prepared.minutes*10);assert.equal(actor.craftingLog.length,1);for(const input of recipe.inputs.filter(i=>i.operation==='Consume')){const consumed=input.ids.reduce((n,id)=>n+before.filter(x=>x.itemId===id).reduce((a,x)=>a+x.qty,0)-e.inventoryItemQty(actor,id),0);assert.ok(consumed>=input.qty,recipe.id+' consumes '+input.label);}for(const id of recipe.toolIds)assert.ok(e.inventoryItemQty(actor,id)>=1,'tool survives');if(recipe.requirements.ritualCaster)assert.equal(actor.slots[1].cur,1);if(recipe.dye)assert.equal(actor.inventory.length,1);else assert.ok(e.inventoryItemQty(actor,choices.resultId)>=recipe.resultQty);const committed=JSON.stringify(e.state().chars);assert.equal((await e.recipesApi.commitGame(prepared)).ok,false);assert.equal(JSON.stringify(e.state().chars),committed);});});
test('stale plans, missing knowledge and combat reject without spending anything',async()=>{const e=await world(),r=e.recipesApi.of('cr_iron_ingot'),{actor,choices}=fixture(e,r);e.setState({items:e.catalogs.items,chars:[actor]});const plan=await e.recipesApi.prepare(r.id,actor.id,choices);assert.equal(plan.ok,true,plan.reason);actor.inventory.find(x=>x.itemId==='it_mat_coal').qty=0;const before=JSON.stringify(e.state().chars);assert.equal((await e.recipesApi.commitGame(plan)).ok,false);assert.equal(JSON.stringify(e.state().chars),before);actor.inventory.find(x=>x.itemId==='it_mat_coal').qty=1;e.state().combat.active=true;assert.equal((await e.recipesApi.prepare(r.id,actor.id,choices)).ok,false);e.state().combat.active=false;const potion=e.recipesApi.of('cr_potion_flying');const f=fixture(e,potion);f.actor.knownRecipes=[];e.setState({items:e.catalogs.items,chars:[f.actor]});assert.match((await e.recipesApi.prepare(potion.id,f.actor.id,f.choices)).reason,/формулу/);});
test('a failed durable save restores inventory, spell slots, history and elapsed world time',async()=>{const e=await world(),r=e.recipesApi.of('cr_holy_water'),{actor,choices}=fixture(e,r);e.setState({items:e.catalogs.items,chars:[actor]});const plan=await e.recipesApi.prepare(r.id,actor.id,choices);assert.equal(plan.ok,true,plan.reason);const before=JSON.stringify(e.state().chars),round=e.state().fxRound;e.recipesApi.failPersistence();const done=await e.recipesApi.commitGame(plan);assert.equal(done.ok,false);assert.equal(JSON.stringify(e.state().chars),before);assert.equal(e.state().fxRound,round);});
test('recipe notes, names and time survive the same export/import contract as the world',async()=>{const e=await world();e.recipesApi.setState({favorites:['cr_iron_ingot'],overrides:{cr_iron_ingot:{name:'Слиток нашей кузницы',note:'Запись мастера',minutes:180}}});const payload=plain(e.itemsApi.export()),restored=await world();restored.setState(payload);const recipe=restored.recipesApi.of('cr_iron_ingot');assert.equal(recipe.name,'Слиток нашей кузницы');assert.equal(recipe.note,'Запись мастера');assert.equal(recipe.durationMinutes,180);assert.equal(recipe.favorite,true);});
test('coloring accepts native game armor and preserves the exact equipped instance',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.dye?.presetResource),{actor,choices}=fixture(e,recipe),index=recipe.inputs.findIndex(i=>i.operation==='Dye');
 assert.ok(recipe.inputs[index].ids.includes('it_holy_shield_life'));
 const target=actor.inventory.find(x=>x.id===choices.entries[index]);Object.assign(target,{itemId:'it_holy_shield_life',notes:'Дар наставника',att:true,charges:2});choices.inputs[index]=target.itemId;
 const unrelated={id:'another-shield',itemId:target.itemId,qty:1,notes:'Другой щит'};actor.inventory.push(unrelated);actor.equipment.OFF_HAND=target.id;
 e.setState({items:e.catalogs.items,chars:[actor]});const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);const done=await e.recipesApi.commitGame(prepared);assert.equal(done.ok,true,done.reason);
 assert.equal(actor.inventory.find(x=>x.id===target.id),target);assert.equal(actor.inventory.find(x=>x.id===unrelated.id),unrelated);assert.equal(target.notes,'Дар наставника');assert.equal(target.charges,2);assert.equal(target.att,true);assert.equal(actor.equipment.OFF_HAND,target.id);assert.equal(target.bg3Dye.recipeId,recipe.id);assert.equal(unrelated.bg3Dye,undefined);
});
test('transforming a stack preserves its remainder and does not merge a crafted result into a special instance',async()=>{
 const e=await world(),recipe=e.recipesApi.rows().find(r=>r.inputs.some(i=>i.operation==='Transform')),{actor,choices}=fixture(e,recipe),index=recipe.inputs.findIndex(i=>i.operation==='Transform'),target=actor.inventory.find(x=>x.id===choices.entries[index]);target.qty=3;target.notes='Отмеченная основа';
 const originalId=target.itemId;e.setState({items:e.catalogs.items,chars:[actor]});const prepared=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(prepared.ok,true,prepared.reason);assert.equal((await e.recipesApi.commitGame(prepared)).ok,true);assert.equal(target.itemId,choices.resultId);assert.equal(target.qty,1);assert.equal(target.notes,'Отмеченная основа');assert.equal(actor.inventory.find(x=>x.id!==target.id&&x.itemId===originalId).qty,2);
 const ingot=e.recipesApi.of('cr_iron_ingot'),f=fixture(e,ingot),special={id:'special-ingot',itemId:ingot.resultIds[0],qty:1,notes:'Наследие',inside:'chest',charges:3};f.actor.inventory.push(special);e.setState({items:e.catalogs.items,chars:[f.actor]});const plan=await e.recipesApi.prepare(ingot.id,f.actor.id,f.choices);assert.equal(plan.ok,true,plan.reason);assert.equal((await e.recipesApi.commitGame(plan)).ok,true);assert.equal(special.qty,1);assert.equal(f.actor.inventory.filter(x=>x.itemId===special.itemId).length,2);
});
test('clones, concurrent confirmations, missing duration and failed station checks cannot spend twice',async()=>{
 const e=await world(),recipe=e.recipesApi.of('cr_iron_ingot'),{actor,choices}=fixture(e,recipe);for(const entry of actor.inventory)if(!recipe.toolIds.includes(entry.itemId))entry.qty*=2;e.setState({items:e.catalogs.items,chars:[actor]});
 const handle=await e.recipesApi.prepare(recipe.id,actor.id,choices),other=await e.recipesApi.prepare(recipe.id,actor.id,choices);assert.equal(handle.ok,true,handle.reason);assert.equal((await e.recipesApi.commitGame({...handle})).ok,false);
 const results=await Promise.all([e.recipesApi.commitGame(handle),e.recipesApi.commitGame(handle),e.recipesApi.commitGame(other)]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(actor.craftingLog.length,1);assert.equal(e.inventoryItemQty(actor,recipe.resultIds[0]),1);
 const station=e.recipesApi.rows().find(r=>r.inputs.some(i=>i.station)),f=fixture(e,station);e.setState({items:e.catalogs.items,chars:[f.actor]});const before=JSON.stringify(e.state().chars);f.choices.stations=[];assert.match((await e.recipesApi.prepare(station.id,f.actor.id,f.choices)).reason,/место работы/);f.choices.stations=station.inputs.map((_,i)=>i);delete f.choices.minutes;assert.match((await e.recipesApi.prepare(station.id,f.actor.id,f.choices)).reason,/длительность/);assert.equal(JSON.stringify(e.state().chars),before);
});

test('renaming an alternative method never splits one result into duplicate cards',()=>{const original=[{id:'a',name:'Зелье лечения',category:'alchemy'},{id:'b',name:'Зелье исцеления',category:'alchemy'}],state=rules.state({overrides:{b:{name:'Формула нашей мастерской'}}}),groups=rules.groups(original.map(r=>rules.applyState(r,state)));assert.equal(groups.length,1);assert.equal(groups[0].methods.length,2);assert.equal(groups[0].methods[1].name,'Формула нашей мастерской');});
