import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import defs from '../scripts/recipe-tabletop-items.js';
import rules from '../scripts/recipe-tabletop-rules.js';
import {loadRuntimeIntegrationEngine} from './helpers/runtime-catalog-loader.mjs';
const root=new URL('../',import.meta.url);
function world(stats){const e=loadRuntimeIntegrationEngine(root),c=e.buildBlank(),t=e.buildBlank();c.id='crafter';c.name='Мастер';c.ab={str:16,dex:16,con:14,int:16,wis:14,cha:12};c.hp=30;c.hpMax=30;c.level=5;c.activeFx=[];t.id='target';t.name='Цель';t.hp=100;t.hpMax=100;t.activeFx=[];t.ab={str:10,dex:10,con:10,int:10,wis:10,cha:10};t.languages=['Общий'];const it=e.catalogs.items.find(x=>x.id===defs.byStats[stats]);assert.ok(it,stats);c.inventory=[{id:'tested',itemId:it.id,qty:2},{id:'weapon',itemId:'it_кинжал',qty:1}];c.equipment={MAIN_HAND:'tested'};e.setState({items:e.catalogs.items,chars:[c,t],activeCharId:c.id,spells:e.catalogs.spells,abilities:e.catalogs.abilities});e.abilitiesApi.quiet();return {e,c,t,it};}
function use(w,id,values={},opts={}){const {e,c,t,it}=w,u=e.itemUseOf(it,id.toLowerCase()),target=u.target==='self'?'ally:'+c.id:'ally:'+t.id,spec=e.itemUseSpecOf(c,it,u,e.targetInfoOf(target),{entryId:'tested',distanceM:1,weaponEntryId:'weapon',...opts});const entered={};for(const r of spec.rows){if(r.natural)entered[r.key]=r.side==='target'?1:15;else if(r.cnt&&r.sides)entered[r.key]=r.cnt;else if(!r.fixed)entered[r.key]=0;if(r.adv)entered[r.key+'_2']=entered[r.key];}Object.assign(entered,values);const out=e.resolveOutcome(spec,entered),rolls=e.tabletopApi.formula(spec,entered,out);assert.equal(rolls.ok,true);return {ok:e.useItemApply('tested',c.id,target,rolls.rolls,u.id,{distanceM:1,weaponEntryId:'weapon',...opts}),spec,out,rolls:rolls.rolls};}
test('all forty reviewed cases resolve to one complete illustrated public game definition',async()=>{
 const e=loadRuntimeIntegrationEngine(root,{fetch:async url=>{const b=fs.readFileSync(new URL(String(url).replace(/^\.\//,''),root));return {ok:true,text:async()=>b.toString(),json:async()=>JSON.parse(b)};}});e.setState(e.catalogs);await e.itemsApi.load();await e.recipesApi.load();
 assert.equal(Object.keys(rules.profiles).length,40);assert.equal(defs.items.find(it=>it.recipeTabletop==='MAG_WATCHER_Human_Crossbow').mechanics.profile.weapon.bg3Properties,undefined);assert.deepEqual(Array.from(e.gameDataAudit(e.catalogs).errors),[]);const rows=e.itemsApi.rows();
 for(const [stats,id]of Object.entries(defs.byStats)){const it=e.itemsApi.resolve(id);assert.ok(it,stats);assert.equal(e.itemsApi.readiness(it).ok,true,stats);assert.ok(rows.some(r=>r.id===id),'public '+stats);assert.match(e.itemsApi.icon(it,40),/<img[^>]+src="assets\//);assert.ok(it.desc.length>90,stats);}
 for(const id of Object.keys(defs.aliases))assert.equal(rows.some(r=>r.id===id),false,'archived alias '+id);
});
for(const [stats,p]of Object.entries(rules.profiles))for(const u of p.actions||[]){if(u.recipeBurst||u.recipeSurface)continue;
 test(stats+' / '+u.id+' commits one use with actual gameplay effects',()=>{
  const w=world(stats),{e,c,it}=w,entry=c.inventory[0];const result=use(w,u.id);assert.equal(result.ok,true,e.elementText('saveStatus')+' '+e.elementText('castErr'));
  assert.equal(entry.qty,u.consume.kind==='item'?1:2);
  if(u.effects?.length)assert.ok(c.activeFx.length||w.t.activeFx.length,it.n);
  if(u.recipeCoating)assert.equal(c.activeFx.find(x=>x.recipeCoating)?.weaponEntryId,'weapon');
  if(u.recipeCooldown)assert.equal(entry.recipeCooldowns[u.id],u.recipeCooldown);
 });
}
test('failed preflight and cancelled targeting never consume recipe products',()=>{const w=world('ALCH_Solution_Oil_Frost'),entry=w.c.inventory[0];assert.equal(use(w,'frost',{}, {weaponEntryId:'missing'}).ok,false);assert.equal(entry.qty,2);assert.equal(w.c.activeFx.length,0);});
test('magic development grants a separately spent slot and cannot be refreshed by another bottle',()=>{const w=world('ALCH_Solution_Elixir_Meditation_Supreme');assert.equal(use(w,'meditation4').ok,true);assert.equal(w.e.tabletopApi.slot(w.c,4)?.recipeSlot.level,4);w.c.recipeMeditationSpent=true;assert.equal(use(w,'meditation4').ok,false);w.e.tabletopApi.rest(w.c,'long');assert.equal(w.e.tabletopApi.slot(w.c,1),undefined);});
test('angelic sleep restores only after two uninterrupted rounds; damage cancels it',()=>{
 const w=world('ALCH_Solution_Potion_Rest_Greater');w.c.hp=3;w.c.slots={1:{cur:0,max:4}};assert.equal(use(w,'angelicGreater').ok,true);w.e.abilitiesApi.advanceFxRound(1);assert.equal(w.c.hp,3);w.e.abilitiesApi.advanceFxRound(1);assert.equal(w.c.hp,30);assert.equal(w.c.slots[1].cur,4);
 const x=world('ALCH_Solution_Potion_Rest_Greater');x.c.hp=10;assert.equal(use(x,'angelicGreater').ok,true);x.e.itemsApi.damage('ally:'+x.c.id,1,'рубящий','удар');x.e.abilitiesApi.advanceFxRound(2);assert.equal(x.c.hp,9);
});
test('burst plans require all targets and human saves; one grenade resolves successes separately',()=>{const {e,c,t,it}=world('OBJ_Bomb_Sunflash');const select={confirmed:true,distance:9,targets:[{key:'ally:'+c.id,distance:2,save:20},{key:'ally:'+t.id,distance:1,save:1}]};const p=e.tabletopApi.burstPlan(c,'tested','sunflash',select);assert.equal(p.ok,true,p.reason);assert.equal(e.tabletopApi.burstCommit(p),true);assert.equal(c.inventory[0].qty,1);assert.equal(c.activeFx.length,0);assert.ok(t.activeFx.some(x=>x.recipeHit==='sunflash'));const bad=e.tabletopApi.burstPlan(c,'tested','sunflash',{...select,targets:[{key:'ally:'+t.id,distance:4,save:1}]});assert.equal(bad.ok,false);assert.equal(c.inventory[0].qty,1);});
function strike(w,entryId='tested',natural=15,save=1){const {e,c,t}=w;if(e.state().combat.active)assert.equal(e.combatWeapon(entryId,'melee'),true,e.elementText('saveStatus'));else e.tabletopApi.weaponOpen(entryId,c.id,'melee');e.setElementValue('castTarget','ally:'+t.id);e.castConfirm();const spec=e.castState().ctx?.spec;assert.ok(spec,e.elementText('castErr'));for(const r of spec.rows){let value=r.natural?(r.side==='target'?save:natural):r.cnt?r.cnt:0;if(r.requiredOnHit&&natural===1)value='';e.setElementValue('cf_'+r.key,value);if(r.adv)e.setElementValue('cf_'+r.key+'_2',value);}e.castFormulaConfirm();assert.equal(e.castState().ctx,null,e.elementText('castErr')+' '+e.elementText('saveStatus'));return spec;}
for(const [stats,p]of Object.entries(rules.profiles).filter(([,p])=>p.onHit||p.coating))test(stats+' has a real on-hit consequence through the protected weapon UI',()=>{const w=world(stats);if(p.coating){assert.equal(use(w,p.actions[0].id).ok,true);w.c.equipment.MAIN_HAND='weapon';}if(p.coating?.fireConversion)w.t.resist=['огонь'];const spec=strike(w,p.coating?'weapon':'tested');assert.ok(w.t.hp<100,'base damage committed');assert.ok(w.t.activeFx.some(x=>x.recipeHit),JSON.stringify(spec.rows));});
test('sussur misses and successful saves do not silence; cancellation spends no attack or item',()=>{for(const [natural,save]of [[1,1],[15,20]]){const w=world('FOR_IncompleteMasterwork_SussurDagger');strike(w,'tested',natural,save);assert.equal(w.t.activeFx.length,0);}const w=world('FOR_IncompleteMasterwork_SussurDagger');w.e.tabletopApi.weaponOpen('tested',w.c.id,'melee');w.e.closeCastModal();assert.equal(w.t.hp,100);assert.equal(w.c.inventory[0].qty,2);});
test('fire damage waits for human dice, repeats on the target turn and cannot replay',()=>{const w=world('OBJ_FireBottle');assert.equal(use(w,'alchemistFire').ok,true);assert.equal(w.t.hp,100);w.e.tabletopApi.startTurn('ally:'+w.t.id);const tick=w.t.recipePendingTicks[0];assert.ok(tick);assert.equal(w.e.tabletopApi.tickResolve('ally:'+w.t.id,tick.id,5),false);assert.equal(w.e.tabletopApi.tickResolve('ally:'+w.t.id,tick.id,3),true);assert.equal(w.t.hp,97);assert.equal(w.e.tabletopApi.tickResolve('ally:'+w.t.id,tick.id,3),false);assert.equal(w.e.tabletopApi.extinguish('ally:'+w.t.id,w.t.activeFx[0].uid,20),true);assert.equal(w.t.activeFx.length,0);});
test('saved source identities migrate in bags, nested contents, ground loot, merchants and chests without losing instance data',()=>{
 const {e}=world('OBJ_DrowPoison'),old=Object.keys(defs.aliases).find(id=>defs.aliases[id]===defs.byStats.OBJ_DrowPoison),make=id=>({id,itemId:old,qty:4,att:true,note:'Личная заметка',valueCp:'1800'}),inner=make('inner'),inventory=make('bag');inventory.inside=[inner];
 const party=[{inventory:[inventory]}],combat={groundItems:[make('ground')],zones:[{itemId:old}]},merchants={instances:[{inventory:[make('shop')]}]},chests={instances:[{container:{lootTable:[make('table')],loot:{draft:{items:[make('draft')]},approved:{items:[make('approved')]}}}}]},db=structuredClone(e.catalogs.items);db.push({id:old,gameDefinition:true,custom:false,n:'Старое имя'});
 const before=JSON.stringify({party,combat,merchants,chests}),r=e.itemsApi.canonicalize(db,party,combat,{merchants,chests});assert.equal(r.remapped,7);assert.equal(JSON.stringify({party,combat,merchants,chests}),before.replaceAll(old,defs.byStats.OBJ_DrowPoison));assert.ok(!db.some(x=>x.id===old));
 assert.equal(e.itemsApi.canonicalize(db,party,combat,{merchants,chests}).remapped,0);
 const custom={id:old,gameDefinition:true,custom:true,n:'Мой собственный яд'};db.push(custom);const owned=make('custom');e.itemsApi.canonicalize(db,[{inventory:[owned]}],{});assert.equal(owned.itemId,old);assert.ok(db.includes(custom));
});
test('opening an older saved world installs new definitions before remapping inventory and is idempotent',async()=>{const w=world('OBJ_DrowPoison'),old=Object.keys(defs.aliases).find(id=>defs.aliases[id]===w.it.id),items=w.e.catalogs.items.filter(it=>!it.recipeTabletop);items.push({id:old,n:'Яд дроу',gameDefinition:true});w.c.inventory[0].itemId=old;w.e.setState({...w.e.state(),items,chars:[w.c,w.t]});await w.e.itemsApi.audit();assert.ok(w.e.itemsApi.resolve(w.it.id));assert.equal(w.c.inventory[0].itemId,w.it.id);assert.equal(w.c.inventory[0].qty,2);const first=JSON.stringify(w.e.state().items.filter(it=>it.recipeTabletop));await w.e.itemsApi.audit();assert.equal(JSON.stringify(w.e.state().items.filter(it=>it.recipeTabletop)),first);});
test('all four meditation slots are separate resources in slots and MP modes; invalid, unprepared and replayed uses are rejected',async()=>{
 for(const [suffix,level]of [['',1],['_Greater',2],['_Superior',3],['_Supreme',4]])for(const mode of ['slots','mp']){
  const w=world('ALCH_Solution_Elixir_Meditation'+suffix),a=w.e.charactersApi;w.c.cls='Волшебник';w.c.level=7;a.characterAdopt(w.c);a.applyClassSlots(w.c);const sp=w.e.catalogs.spells.find(s=>s.id==='sp_magic_missile');w.c.spellbook=[{spellId:sp.id,access:'spellbook',prep:true}];if(mode==='mp')assert.equal((await a.magicSwitch('mp')).success,true);
  assert.equal(use(w,'meditation'+level).ok,true);const before=JSON.stringify([w.c.slots,w.c.magicResource]);for(const bad of ['free','1oops','1.5','0','5:recipe'])assert.equal(a.slotPlanFor(w.c,sp,bad).ok,false,bad);
  w.c.spellbook[0].prep=false;assert.equal(a.slotPlanFor(w.c,sp,level+':recipe').ok,false);w.c.spellbook[0].prep=true;const plan=a.slotPlanFor(w.c,sp,level+':recipe');assert.equal(plan.ok,true,plan.reason);assert.equal(plan.lv,level);a.commitSlotPlan(w.c,plan);assert.equal(JSON.stringify([w.c.slots,w.c.magicResource]),before);assert.throws(()=>a.commitSlotPlan(w.c,plan));assert.equal(use(w,'meditation'+level).ok,false);
 }
});
test('arcane acuity changes real spell attacks and DCs, loses two on damage and recovers at turn start',()=>{const w=world('ALCH_Solution_Elixir_ArcaneAcuity'),sp=w.e.catalogs.spells.find(s=>s.id==='sp_ray_frost'),spec=()=>w.e.rollSpecOf(sp,{kind:'spell',caster:w.c,target:w.e.targetInfoOf('ally:'+w.t.id)});const before=spec().rows.find(r=>r.type==='atk').mod;assert.equal(use(w,'acuity').ok,true);assert.equal(spec().rows.find(r=>r.type==='atk').mod,before+3);w.e.itemsApi.damage('ally:'+w.c.id,1,'огонь','проверка');assert.equal(spec().rows.find(r=>r.type==='atk').mod,before+1);w.e.tabletopApi.startTurn('ally:'+w.c.id);assert.equal(spec().rows.find(r=>r.type==='atk').mod,before+3);});
test('freedom blocks magical restraint and slowness while movement and escape spend their actual budget',()=>{const w=world('ALCH_Solution_Elixir_Freedom');w.c.speed='9 м';assert.equal(use(w,'freedom').ok,true);w.e.tabletopApi.applyFx(w.c.id,{k:'spell',id:'test',fx:[{stat:'condition',mode:'text',value:'Парализованный'},{stat:'speed',mode:'mul',value:0.5}]});assert.ok(!w.e.effectiveConditions(w.c).includes('Парализованный'));assert.equal(w.e.charactersApi.speedTotal(w.c),'9 м');startCombat(w);assert.equal(w.e.tabletopApi.move(w.c,3,'walk',false,true).cost,3);w.e.tabletopApi.condition('ally:'+w.c.id,'Захваченный');assert.equal(w.e.tabletopApi.escape(w.c.id),true);assert.equal(w.e.state().combat.turn.movementUsed,4.5);assert.ok(!w.e.effectiveConditions(w.c).includes('Захваченный'));assert.equal(w.e.tabletopApi.move(w.c,6).ok,false);});
test('jumping is stronger but cannot exceed movement; enlarged size changes heavy-weapon handling and carrying',()=>{const w=world('ALCH_Solution_Potion_Jump');w.c.speed='9 м';const before=w.e.tabletopApi.jump(w.c,false).long;assert.equal(use(w,'jump').ok,true);assert.equal(w.e.tabletopApi.jump(w.c,false).long,before*3);startCombat(w);assert.equal(w.e.tabletopApi.move(w.c,6,'long',true).ok,true);assert.equal(w.e.state().combat.turn.movementUsed,9);assert.equal(w.e.tabletopApi.move(w.c,1).ok,false);const x=world('ALCH_Solution_Elixir_Enlarge');x.c.size='Маленький';assert.equal(use(x,'enlarge').ok,true);assert.equal(x.e.tabletopApi.size(x.c).name,'Средний');assert.ok(x.e.itemsApi.effects(x.c).some(f=>f.stat==='carry'&&f.value===2));});
test('Malice is inhaled, requires every save die, uses poison immunity, and cleansing removes linked blindness',()=>{const w=world('OBJ_Malice');w.t.activeFx=[{uid:'bless',fx:[{stat:'save',mode:'die',value:'1d4'},{stat:'save.con',mode:'adv',value:1}]}];w.e.setState({...w.e.state(),chars:[w.c,w.t]});const selection={confirmed:true,distance:1,targets:[{key:'ally:'+w.t.id,distance:0.7,save:1}]};assert.equal(w.e.tabletopApi.burstPlan(w.c,'tested','malice',selection).ok,false);const rule=w.e.tabletopApi.burstSave(w.c,w.it,w.e.targetInfoOf('ally:'+w.t.id),rules.profiles.OBJ_Malice.burst).rule;selection.targets[0].save2=2;selection.targets[0].dice=Object.fromEntries(rule.dice.map(d=>[d.key,1]));const p=w.e.tabletopApi.burstPlan(w.c,'tested','malice',selection);assert.equal(p.ok,true,p.reason);assert.equal(w.e.tabletopApi.burstCommit(p),true);assert.ok(w.e.effectiveConditions(w.t).includes('Ослепленный'));w.e.tabletopApi.cleanse(w.t,['Отравленный']);assert.ok(!w.e.effectiveConditions(w.t).includes('Ослепленный'));assert.equal(w.e.tabletopApi.burstCommit(p),false);});
test('a sunflash expiration produces a short afterimage penalty rather than permanent blindness',()=>{const w=world('OBJ_Bomb_Sunflash'),p=w.e.tabletopApi.burstPlan(w.c,'tested','sunflash',{confirmed:true,distance:3,targets:[{key:'ally:'+w.t.id,distance:2,save:1}]});assert.equal(w.e.tabletopApi.burstCommit(p),true);assert.equal(w.e.abilitiesApi.advanceFxRound(10),true);assert.ok(!w.e.effectiveConditions(w.t).includes('Ослепленный'));assert.ok(w.t.activeFx.some(x=>x.recipeAfterFlash));assert.equal(w.e.abilitiesApi.advanceFxRound(1),true);assert.equal(w.t.activeFx.length,0);});
test('Drow poison remains until a wound, spends one delivered dose and wakes without curing poison',()=>{const w=world('OBJ_DrowPoison');assert.equal(use(w,'drow').ok,true);w.c.equipment.MAIN_HAND='weapon';strike(w,'weapon',1);assert.ok(w.c.activeFx.some(x=>x.recipeCoating));strike(w,'weapon',15,1);assert.ok(!w.c.activeFx.some(x=>x.recipeCoating));assert.ok(w.e.effectiveConditions(w.t).includes('Бессознательный'));assert.equal(w.e.tabletopApi.wake('ally:'+w.t.id,w.t.activeFx.find(x=>x.recipePoisonSleep).uid,w.c.id,1),true);assert.ok(!w.e.effectiveConditions(w.t).includes('Бессознательный'));assert.ok(w.e.effectiveConditions(w.t).includes('Отравленный'));});
test('pending periodic damage blocks time skips and advancing turns until human dice are entered',()=>{const w=world('OBJ_FireBottle');use(w,'alchemistFire');const r=w.e.state().fxRound;assert.equal(w.e.abilitiesApi.advanceFxRound(10),false);assert.equal(w.e.state().fxRound,r);assert.equal(w.e.abilitiesApi.advanceFxRound(1),true);assert.equal(w.e.abilitiesApi.advanceFxRound(1),false);const tick=w.t.recipePendingTicks[0];assert.equal(w.e.tabletopApi.tickResolve('ally:'+w.t.id,tick.id,2),true);assert.equal(w.e.abilitiesApi.advanceFxRound(1),true);});
test('haste grants only one extra weapon attack and leaving/reentering never refreshes it',()=>{const w=world('ALCH_Solution_Grenade_SporesHaste');startCombat(w);const p=w.e.tabletopApi.burstPlan(w.c,'tested','hastespores',{confirmed:true,distance:3,targets:[{key:'ally:'+w.c.id,distance:1}]});assert.equal(w.e.tabletopApi.burstCommit(p),true);const z=w.e.state().combat.zones[0];w.c.equipment.MAIN_HAND='weapon';assert.equal(w.e.state().combat.turn.recipeExtraAttacks,1);assert.equal(w.e.tabletopApi.zoneMember(z.id,'ally:'+w.c.id,4),true);assert.equal(w.e.state().combat.turn.recipeExtraAttacks,0);assert.equal(w.e.tabletopApi.zoneMember(z.id,'ally:'+w.c.id,1),true);strike(w,'weapon');assert.equal(w.e.state().combat.turn.recipeExtraAttacks,0);assert.equal(w.e.state().combat.turn.recipeHasteSpent,true);w.e.tabletopApi.zoneMember(z.id,'ally:'+w.c.id,4);w.e.tabletopApi.zoneMember(z.id,'ally:'+w.c.id,1);assert.equal(w.e.state().combat.turn.recipeExtraAttacks,0);assert.equal(w.e.combatCanSpend('attack','ally:'+w.c.id,true),false);assert.equal(w.e.combatCanSpend('action','ally:'+w.c.id,true),false);});
test('thought reading works on actual foe records and records the GM answer without inventing it',()=>{const w=world('ALCH_Solution_Potion_DetectThoughts'),f=structuredClone(w.e.catalogs.foes.find(f=>(f.abil?.int||0)>=4&&f.langs&&f.langs!=='—'));assert.ok(f);w.e.state().foes.push(f);use(w,'thoughts');const uid=w.c.activeFx[0].uid;assert.equal(w.e.tabletopApi.conversation(w.c,uid,'foe:'+f.id,10,false,null,'Сведения').ok,false);assert.equal(w.e.tabletopApi.conversation(w.c,uid,'foe:'+f.id,3,false,null,'Ищет потерянный ключ').ok,true);assert.ok(w.e.state().journal.some(j=>j.text.includes('Ищет потерянный ключ')));});

function startCombat(w){const f=structuredClone(w.e.catalogs.foes[0]);f.id='opponent';f.hp=100;f.hpMax=100;w.e.state().foes.push(f);assert.equal(w.e.combatStart([{kind:'ally',id:w.c.id,nat:20},{kind:'foe',id:f.id,nat:1}]),true,w.e.elementText('saveStatus'));return f;}
test('contact poison persists on one object, washes off, and exposes exactly one creature',()=>{const w=world('OBJ_CrawlerMucus');assert.equal(w.e.tabletopApi.surface(w.c,'tested','weapon').ok,true);assert.equal(w.c.inventory[0].qty,1);const object=w.c.inventory.find(x=>x.id==='weapon');assert.ok(object.recipeContactPoison);assert.equal(w.e.tabletopApi.surface(w.c,'tested','weapon').ok,false);const values={recipe_burst_save:1};assert.equal(w.e.tabletopApi.contact(w.c,'weapon','ally:'+w.t.id,{}),false);assert.ok(object.recipeContactPoison);assert.equal(w.e.tabletopApi.contact(w.c,'weapon','ally:'+w.t.id,values),true);assert.ok(!object.recipeContactPoison);assert.ok(w.e.effectiveConditions(w.t).includes('Парализованный'));assert.equal(w.e.tabletopApi.contact(w.c,'weapon','ally:'+w.t.id,values),false);assert.equal(w.e.tabletopApi.surface(w.c,'tested','weapon').ok,true);assert.equal(w.e.tabletopApi.contact(w.c,'weapon',null,null,true),true);assert.ok(!object.recipeContactPoison);});
test('Mourning Frost adds cold damage once, rolls the separate chilling save and scales its ray by level',()=>{const w=world('MAG_Cold_IncreaseColdDamageOnCast_Staff'),r=use(w,'rayFrost');assert.equal(r.ok,true);assert.equal(r.spec.rows.find(r=>r.type==='dmg').cnt,2);assert.equal(w.t.hp,97);assert.ok(w.t.activeFx.some(e=>e.recipeHit==='chilled'));assert.equal(w.e.charactersApi.dmgAfterTraits(w.t,10,'холод').amount,20);assert.equal(w.e.charactersApi.dmgAfterTraits(w.t,10,'огонь').amount,5);});
test('combustion resolves one shared human damage roll with individual saves and fire defenses',()=>{const w=world('ALCH_Solution_Oil_Combustion');use(w,'combustion');w.c.equipment.MAIN_HAND='weapon';strike(w,'weapon');w.e.itemsApi.damage('ally:'+w.t.id,1,'огонь','поджог');const pending=w.c.recipePendingBursts[0];assert.ok(pending);const before=w.t.hp;w.c.immune=['огонь'];const p=w.e.tabletopApi.burstPlan(w.c,null,null,{confirmed:true,distance:0,damage:12,targets:[{key:'ally:'+w.t.id,distance:0,save:20},{key:'ally:'+w.c.id,distance:1,save:1}]},pending.id);assert.equal(p.ok,true,p.reason);assert.equal(w.e.tabletopApi.burstCommit(p),true);assert.equal(w.t.hp,before-6);assert.equal(w.c.hp,30);assert.equal(w.c.recipePendingBursts.length,0);assert.equal(w.e.tabletopApi.burstCommit(p),false);});
test('fire conversion retains immunity and flat reduction instead of blindly doubling all damage',()=>{const w=world('ALCH_Solution_Oil_RemoveResistanceFire');w.t.resist=['огонь'];w.t.activeFx=[{uid:'ward',fx:[{stat:'damage.reduction',mode:'grant',value:{types:['огонь'],amount:3}}]}];use(w,'arson');w.c.equipment.MAIN_HAND='weapon';strike(w,'weapon');assert.equal(w.e.charactersApi.dmgAfterTraits(w.t,10,'огонь').amount,17);w.t.immune=['огонь'];assert.equal(w.e.charactersApi.dmgAfterTraits(w.t,10,'огонь').amount,0);});
test('shadow lantern produces an allied combatant with a real attack and expires with its summon',()=>{const w=world('Quest_GLO_Moonlantern_Gale');startCombat(w);assert.equal(use(w,'shadow').ok,true);const shade=w.e.state().foes.find(f=>f.recipeShadow);assert.ok(shade);assert.equal(shade.summonSide,'ally');assert.ok(w.e.state().combat.order.some(e=>e.id===shade.id));assert.ok(w.e.foeActionsOf(shade).some(a=>a.damage?.[0]?.cnt===2));assert.ok(w.e.itemsApi.effects(w.c).some(f=>f.stat==='light.bright'&&f.value===3));assert.equal(use(w,'shadow').ok,false);w.e.abilitiesApi.advanceFxRound(600);assert.ok(!w.e.state().foes.some(f=>f.recipeShadow));});
test('tadpole activation follows mental spells, concentration advantage persists, and see-invisibility adjusts attacks',()=>{const w=world('ALCH_Solution_Elixir_Tadpole');use(w,'tadpole');w.e.tabletopApi.spellTrigger(w.c,{s:'Воплощение'});assert.ok(!w.c.activeFx.some(e=>e.recipeHit==='psionicEmpowerment'));w.e.tabletopApi.spellTrigger(w.c,{s:'Прорицание'});assert.ok(w.c.activeFx.some(e=>e.recipeHit==='psionicEmpowerment'));const x=world('ALCH_Solution_Elixir_Concentration');use(x,'concentration');assert.ok(x.e.charactersApi.rollFxEntries(x.c,'save.con',['concentration']).some(f=>f.mode==='adv'));const y=world('ALCH_Solution_Elixir_SeeInvisible');y.t.cond=['Невидимый'];const weapon=y.e.itemsApi.resolve('it_кинжал');assert.equal(y.e.weaponSpecOf(y.c,weapon,y.e.targetInfoOf('ally:'+y.t.id),{entryId:'weapon'}).rows[0].adv,2);use(y,'seeInvisible');assert.equal(y.e.weaponSpecOf(y.c,weapon,y.e.targetInfoOf('ally:'+y.t.id),{entryId:'weapon'}).rows[0].adv,0);});
test('bloodlust allows one extra weapon attack on a hostile kill, never a free spell or ally-summon reward',()=>{const w=world('ALCH_Solution_Elixir_Bloodlust');w.c.cls='Волшебник';use(w,'bloodlust');w.c.equipment.MAIN_HAND='weapon';const f=startCombat(w);f.hp=1;const target=w.t;w.t=f;w.t.id=f.id;strikeTarget(w,'weapon','foe:'+f.id);const turn=w.e.state().combat.turn;assert.equal(turn.recipeBloodlust,true);assert.equal(turn.recipeExtraAttacks,1);assert.equal(w.c.hpTemp,5);assert.equal(w.e.combatCanSpend('action','ally:'+w.c.id,true),false);w.t=target;strike(w,'weapon');assert.equal(turn.recipeExtraAttacks,0);assert.equal(w.e.combatCanSpend('attack','ally:'+w.c.id,true),false);});
function strikeTarget(w,entryId,key,mode='melee',natural=15,save=1){const {e,c}=w;if(e.state().combat.active)assert.equal(e.combatWeapon(entryId,mode),true,e.elementText('saveStatus'));else e.tabletopApi.weaponOpen(entryId,c.id,mode);e.setElementValue('castTarget',key);e.castConfirm();if(mode==='ranged')e.castDistanceSet('far');const spec=e.castState().ctx?.spec;assert.ok(spec,e.elementText('castErr'));for(const r of spec.rows){const v=r.natural?(r.side==='target'?save:natural):r.cnt?r.cnt:0;e.setElementValue('cf_'+r.key,v);if(r.adv)e.setElementValue('cf_'+r.key+'_2',v);}e.castFormulaConfirm();assert.equal(e.castState().ctx,null,e.elementText('castErr')+' '+e.elementText('saveStatus'));return spec;}
test('Hellfire crossbow spends bolts, pulls on a failed save, and commits one lightning burst even on a miss',()=>{const w=world('MAG_WATCHER_Human_Crossbow'),bolt=w.e.catalogs.items.find(x=>/болты/i.test(x.n)&&w.e.itemProfile(x).ammo);assert.ok(bolt,'bolt item');w.c.inventory.push({id:'bolts',itemId:bolt.id,qty:10});w.c.position={x:0,y:0};w.t.position={x:15,y:0};assert.equal(use(w,'harpoonReady').ok,true);strikeTarget(w,'tested','ally:'+w.t.id,'ranged');assert.equal(w.c.inventory.find(e=>e.id==='bolts').ammoSpent,1);assert.equal(w.t.position.x,6);assert.equal(use(w,'harpoonReady').ok,false);w.e.tabletopApi.rest(w.c,'short');assert.equal(use(w,'lightningReady').ok,true);const before=w.t.hp;strikeTarget(w,'tested','ally:'+w.t.id,'ranged',1);assert.equal(w.t.hp,before-2);assert.equal(w.c.recipePendingBursts.length,1);assert.equal(use(w,'lightningReady').ok,false);});

test('short recipe conditions expire in world time after combat ends',()=>{const w=world('MAG_Cold_IncreaseColdDamageOnCast_Staff');startCombat(w);assert.equal(use(w,'rayFrost').ok,true);const slow=w.t.activeFx.find(e=>e.durationKind==='targetStart');assert.ok(slow);assert.equal(w.e.combatEnd(true),true);assert.equal(slow.expiresAtRound,w.e.state().fxRound+1);assert.equal(w.e.abilitiesApi.advanceFxRound(1),true);assert.ok(!w.t.activeFx.includes(slow));});

test('saved manual item descriptions survive every audit including short text',async()=>{const w=world('OBJ_DrowPoison'),dagger=w.e.itemsApi.resolve('it_кинжал');dagger.desc='Кинжал хранителя.';dagger.custom=true;await w.e.itemsApi.audit();assert.equal(dagger.desc,'Кинжал хранителя.');await w.e.itemsApi.audit();assert.equal(dagger.desc,'Кинжал хранителя.');});
