"""Extract only ability names from the publisher's glossary; preserve cell provenance.

Usage: python scripts/extract-hobbyworld-ability-terms.py path/to/Glossary5E_2.xlsx
The workbook is a read-only source, not redistributed with the project.
"""
import hashlib
import json
import pathlib
import sys
import openpyxl

source = pathlib.Path(sys.argv[1])
workbook = openpyxl.load_workbook(source, read_only=True, data_only=True)
sheet = workbook['Парам. перс']
terms = []
for row, values in enumerate(sheet.values, 1):
    english, russian, kind = (list(values) + [None] * 3)[:3]
    if isinstance(english, str) and isinstance(russian, str) and kind in ['Класс. особенность', 'особенность расы', 'черта']:
        terms.append({'english': english.strip(), 'russian': russian.strip(), 'kind': kind, 'cell': f'B{row}'})
# Spellcasting is a rules term, separately from the monster trait of the same name.
general = workbook['Осн. терм']
for row, english in [(196, 'Spellcasting'), (67, 'Darkvision'), (15, 'Alignment'), (37, 'Cantrip'), (191, 'Speed')]:
    assert general[f'A{row}'].value.strip() == english
    terms.append({'english': english, 'russian': general[f'B{row}'].value.strip(), 'kind': 'термин', 'sheet': general.title, 'cell': f'B{row}'})
prose_terms = []
for row in [37, 128, 176, 182, 251, 267]:
    prose_terms.append({'english': general[f'A{row}'].value.strip(), 'russian': general[f'B{row}'].value.strip(), 'sheet': general.title, 'cell': f'B{row}'})
payload = {'source': 'https://hobbyworld.ru/download/rules/Glossary5E_2.xlsx',
           'sha256': hashlib.sha256(source.read_bytes()).hexdigest(), 'sheet': sheet.title, 'terms': terms, 'proseTerms': prose_terms}
dest = pathlib.Path(__file__).resolve().parent / 'hobbyworld-ability-terms.js'
dest.write_text('// Generated by extract-hobbyworld-ability-terms.py; short terminology entries only.\n'
                + 'globalThis.DND_HOBBYWORLD_ABILITY_TERMS = ' + json.dumps(payload, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'{len(terms)} terms -> {dest.name}')
