(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.DndRecipeRules=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const CATEGORIES={extract:'Экстракты',alchemy:'Алхимия',dye:'Окрашивание',craft:'Изготовление',material:'Материалы',ritual:'Обряды'};
const CATEGORY_INPUTS={ALCH_Affinity_Air:'Любой сублимат',ALCH_Affinity_Earth:'Любые соли',ALCH_Affinity_Fey:'Любая эссенция',ALCH_Affinity_Fire:'Любая зола',ALCH_Affinity_Shadow:'Любой купорос',ALCH_Affinity_Water:'Любая суспензия',ConstructPart:'Деталь механизма',Drink:'Напиток',DyableArmor:'Окрашиваемая экипировка'};
// Approved game rules: alternative formulas produce the existing tabletop item.
// Keep source records and formula knowledge intact; never infer aliases by name.
const TABLETOP_RESULTS=Object.freeze({
'bg3:recipe:ALCH_Potion_HealingGreater_Balsam':'it_potion_great_heal',
'bg3:recipe:ALCH_Potion_HealingSuperior_YellowMuskCreeper':'it_potion_healing_superior',
'bg3:recipe:ALCH_Potion_HealingSupreme_KiRinHair':'it_potion_healing_supreme',
'bg3:recipe:ALCH_Potion_Invisibility_ImpPatagium':'it_potion_invisibility',
'bg3:recipe:ALCH_Potion_Flying_EagleFeather':'it_potion_flying',
'bg3:recipe:ALCH_Potion_Antidote_Mugwort':'it_противоядие'
});
const TABLETOP_INGREDIENTS=Object.freeze({WPN_Greatsword:'it_двуручный_меч',WPN_Dagger:'it_кинжал',WPN_Sickle:'it_серп'});
// These combinations create an item. Other quest combinations operate a scene,
// lock, altar or puzzle; they are retained in source data, never sold as recipes.
const CRAFT_IDS=new Set(['QUEST_FOR_CultistsRepairedSpear','QUEST_FOR_SussurGreatsword','QUEST_FOR_SussurDagger','QUEST_FOR_SussurSickle','QUEST_DEN_ApprenticeAntidote','UNI_ThreeDrow_Sraff','QUEST_WYR_SharranInformer_MagicRing','MOO_BalthazarLab_Circle','UNI_LOW_SteelWatchFoundry_WatcherHarpoonCrossbow','UNI_LOW_BaldursMouth_LoadPrinter']);
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
const key=s=>String(s||'').normalize('NFKC').toLocaleLowerCase('ru').replace(/ё/g,'е').replace(/[«»„“”"']/g,'').replace(/исцеления/g,'лечения').replace(/\s+/g,' ').trim();
function scope(recipe){const id=String(recipe.name||recipe.id||'').replace(/^bg3:recipe:/,'');if(id.startsWith('BASE_'))return {kind:'template',reason:'Служебный шаблон; не задаёт конкретное изготовление.'};if(recipe.manualReasons?.length)return {kind:'unresolved',reason:'В исходных данных отсутствует конкретный ингредиент; сохранено для связанного события.'};if(id.startsWith('ALCH_')||recipe.dye||CRAFT_IDS.has(id))return {kind:'recipe',reason:'Полный состав и конкретный результат изготовления.'};return {kind:'scene',reason:'Взаимодействие с объектом или событием мира, а не изготовление предмета.'};}
function state(raw){const out={version:1,overrides:{},favorites:[]};if(!raw||typeof raw!=='object')return out;for(const [id,row] of Object.entries(raw.overrides||{})){if(!row||typeof row!=='object')continue;out.overrides[id]={name:String(row.name||'').slice(0,180),note:String(row.note||'').slice(0,4000),minutes:row.minutes==null?null:Number(row.minutes)};if(!Number.isSafeInteger(out.overrides[id].minutes)||out.overrides[id].minutes<0||out.overrides[id].minutes>525600)out.overrides[id].minutes=null;}out.favorites=[...new Set((Array.isArray(raw.favorites)?raw.favorites:[]).filter(x=>typeof x==='string'))];return out;}
function inputGroups(inputs){const groups=new Map();for(const input of inputs){const ids=[...new Set(input.ids)],signature=JSON.stringify([ids.slice().sort(),input.operation,input.category||'']);let group=groups.get(signature);if(!group){group={...input,ids,qty:0,slots:[]};groups.set(signature,group);}group.qty+=input.qty||1;group.slots.push(...(input.slots||[input.slot]));}return [...groups.values()];}
function local(recipe,lookup,minutes){const result=lookup(recipe.result.itemId),requirements=clone(recipe.requirements||{});return {id:recipe.id,source:'game',binding:'craft',name:recipe.n,category:requirements.ritualCaster?'ritual':/^cr_(?:alchemical_base|iron|silver|steel|cured|hardwood)/.test(recipe.id)?'material':recipe.toolIds.some(id=>['it_tool_herbalism','it_tool_alchemist','it_tool_poisoner'].includes(id))?'alchemy':'craft',description:recipe.note||'',durationMinutes:minutes,toolIds:recipe.toolIds.slice(),requirements,inputs:inputGroups(recipe.inputs.map((input,index)=>({slot:index+1,ids:[input.itemId],label:lookup(input.itemId)?.n||'Материал',operation:'Consume',qty:input.qty}))),resultIds:[recipe.result.itemId],resultQty:recipe.result.qty,iconItem:result,formulaRequired:requirements.formulaRequired===true,raw:recipe};}
function imported(recipe,lookup,links){if(scope(recipe).kind!=='recipe')return null;const link=links?.recipes?.[recipe.id],dye=recipe.dye,tabletopResult=TABLETOP_RESULTS[recipe.id],resultIds=tabletopResult?[tabletopResult]:(link?.resultIds||recipe.result.candidateIds).slice(),paint=dye&&recipe.inputs.find(i=>i.transform==='Consume'),paintLink=paint&&link?.inputs.find(i=>i.slot===paint.slot),iconIds=dye?(paintLink?.ids||paint?.candidateIds):resultIds,iconItem=(iconIds||[]).map(lookup).find(Boolean)||(!dye&&recipe.result.candidateIds.map(lookup).find(Boolean)),name=dye?(dye.presetResource?'Окрашивание: '+(iconItem?.n||'краска'):'Удаление краски'):(iconItem?.n||'');
if(!name)return null;const category=dye?'dye':recipe.alchemyType==='IngredientsToExtract'?'extract':recipe.name.startsWith('ALCH_')?'alchemy':'craft';
const inputs=inputGroups(recipe.inputs.map(i=>{const selected=link?.inputs.find(row=>row.slot===i.slot),canonicalIds=(selected?.ids||i.candidateIds).slice(),aliases=(selected?.aliases||[]).slice();return {slot:i.slot,ids:canonicalIds.concat(aliases),canonicalIds,aliases,label:i.type==='Category'?(CATEGORY_INPUTS[i.symbol]||'Подходящий ингредиент'):(canonicalIds.map(lookup).find(Boolean)?.n||''),operation:i.transform,category:i.type==='Category'?i.symbol:'',qty:1};}));
const composition=inputs.map(i=>i.label+' ×'+i.qty).join(', '),description=dye?(dye.presetResource?'Нанесите выбранную краску на один конкретный предмет экипировки. Его свойства, настройка и заметки сохранятся.':'Удалите окраску с одного конкретного предмета. Его свойства, настройка и заметки сохранятся.'):category==='extract'?'Обработайте ингредиенты: '+composition+'. Полученный экстракт используется в дальнейших рецептах.':'Соедините компоненты: '+composition+'. Расход и сохранение каждого компонента указаны в составе.';
return {id:recipe.id,source:'game',binding:'combination',name,category,description,durationMinutes:null,toolIds:[],requirements:{},inputs,resultIds:dye?[]:resultIds,resultQty:recipe.result.qty,iconItem,formulaRequired:recipe.accessPolicy?.mode==='exact-formula-required',dye:clone(dye),raw:recipe};}
function applyState(recipe,s){const change=s?.overrides?.[recipe.id]||{};return {...recipe,groupName:recipe.name,name:change.name||recipe.name,note:change.note||'',durationMinutes:Object.prototype.hasOwnProperty.call(change,'minutes')?change.minutes:recipe.durationMinutes,favorite:!!s?.favorites?.includes(recipe.id)};}
function groups(recipes){const map=new Map();for(const recipe of recipes){const id=recipe.dye?'dye:'+key(recipe.groupName||recipe.name):recipe.resultIds?.length?'result-items:'+JSON.stringify([...new Set(recipe.resultIds)].sort()):'result:'+key(recipe.groupName||recipe.name),row=map.get(id)||{id,name:recipe.name,category:recipe.category,iconItem:recipe.iconItem,methods:[]};row.methods.push(recipe);map.set(id,row);}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'ru'));}
function ingredientStatus(recipe,actor){return recipe.inputs.map(input=>({...input,have:(actor?.inventory||[]).filter(e=>input.ids.includes(e.itemId)).reduce((n,e)=>n+(Number.isSafeInteger(e.qty)&&e.qty>0?e.qty:0),0)}));}
function fail(reason,code){return {ok:false,reason,code:code||'RECIPE_INVALID'};}
// Pure inventory planning: shared pools are reserved before anything is consumed.
// Exact components are allocated before broad categories, and all instance
// changes are prepared on a copy. A failed choice cannot spend ingredients.
function plan(recipe,actor,choices={}){
if(!actor||!Array.isArray(actor.inventory))return fail('Выберите героя.');if(!recipe||!recipe.inputs?.length)return fail('Рецепт не содержит состава.');
const entries=actor.inventory,ids=new Set();for(const e of entries){if(!e||typeof e.id!=='string'||ids.has(e.id)||e.qty==null||e.qty===''||!Number.isSafeInteger(Number(e.qty))||Number(e.qty)<0)return fail('В инвентаре есть повреждённая запись.');ids.add(e.id);}
const pools=new Map(entries.map(e=>[e.id,Number(e.qty)])),allocated=[],selected={};
const ordered=recipe.inputs.map((input,index)=>({input,index})).sort((a,b)=>a.input.ids.length-b.input.ids.length||a.index-b.index);
for(const {input,index} of ordered){if(!Number.isSafeInteger(input.qty)||input.qty<1||!['Consume','None','Transform','Dye'].includes(input.operation))return fail('Некорректная операция в составе.');
const requested=choices.inputs?.[index],entryId=choices.entries?.[index];if(requested&&!input.ids.includes(requested))return fail('Выбранный ингредиент не подходит рецепту.');
if(input.category&&!requested)return fail('Выберите компонент: '+input.label+'.','CHOICE_REQUIRED');
let candidates=entries.filter(e=>input.ids.includes(e.itemId)&&(!requested||e.itemId===requested)&&(!entryId||e.id===entryId)&&(pools.get(e.id)||0)>0);
if(['Dye','Transform'].includes(input.operation)){if(input.qty!==1)return fail('Преобразование требует одного экземпляра.');if(!entryId&&candidates.length>1)return fail('Выберите конкретный экземпляр: '+input.label+'.','ENTRY_REQUIRED');if(input.operation==='Dye'&&Number(candidates[0]?.qty)!==1)return fail('Для окрашивания сначала отделите один предмет от стопки.','SPLIT_REQUIRED');}
let left=input.qty;for(const e of candidates){const qty=Math.min(left,pools.get(e.id));if(qty){allocated.push({entryId:e.id,itemId:e.itemId,qty,operation:input.operation,input:index});pools.set(e.id,pools.get(e.id)-qty);left-=qty;}if(!left)break;}
if(left)return fail('Не хватает «'+input.label+'»: нужно '+input.qty+', доступно '+(input.qty-left)+'.','MISSING_INPUT');selected[index]=requested||candidates[0]?.itemId;
}
const transforms=allocated.filter(x=>x.operation==='Transform'),dyes=allocated.filter(x=>x.operation==='Dye');if(transforms.length>1||dyes.length>1||transforms.length&&dyes.length)return fail('Неоднозначное преобразование предметов.');
if(transforms.length&&recipe.resultQty!==1)return fail('Преобразование должно давать один экземпляр.');
let resultId=null;if(!recipe.dye){resultId=choices.resultId||(recipe.resultIds.length===1?recipe.resultIds[0]:null);if(!resultId||!recipe.resultIds.includes(resultId))return fail('Выберите результат изготовления.','RESULT_REQUIRED');if(!Number.isSafeInteger(recipe.resultQty)||recipe.resultQty<1)return fail('Некорректное количество результата.');}
return {ok:true,recipeId:recipe.id,allocated,selected,resultId,resultQty:recipe.resultQty,transform:transforms[0]||null,dye:dyes[0]||null,deductions:allocated.filter(x=>x.operation==='Consume'),inventorySnapshot:JSON.stringify(actor.inventory),equipmentSnapshot:JSON.stringify(actor.equipment||{})};
}
return Object.freeze({CATEGORIES,CATEGORY_INPUTS,TABLETOP_RESULTS,TABLETOP_INGREDIENTS,CRAFT_IDS,scope,state,key,clone,local,imported,applyState,groups,ingredientStatus,inputGroups,plan});
});
