'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright')));}
const root=path.resolve(__dirname,'..',process.env.QA_SITE_ROOT||'.'),output=path.resolve(process.env.QA_ARTIFACT_DIR||path.join(__dirname,'evidence','game-recipes'),'browser');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/(?:dnd-world\/)?/,''),file=path.resolve(root,relative||'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404).end();return;}res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,channel:process.env.QA_BROWSER_CHANNEL||undefined});let page;
 try{
  page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(45000);const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('dialog',d=>d.accept());await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  const ready=async()=>page.getByRole('button',{name:'✠ Новый герой',exact:true}).or(page.getByRole('button',{name:'← К списку героев',exact:true})).first().waitFor({timeout:120000});
  await page.goto(base,{waitUntil:'domcontentloaded'});await ready();await page.locator('#itemsTabButton').click();await page.locator('#bg3ReleaseMetrics[data-catalog-state="ready"]').waitFor({timeout:120000});await page.getByRole('tab',{name:/^Рецепты/}).click();await page.locator('[data-game-recipes="193"]').waitFor();
  assert.equal(await page.getByRole('tab',{name:/^Рецепты/}).innerText(),'Рецепты · 193');
  assert.doesNotMatch(await page.locator('.recipe-workbench').innerText(),/предметов кампании|предметов каталога|Шепчущая маска/);
  // Fixtures only provision a hero and ingredients. Manufacturing uses actual controls.
  const seed=async(id,nativeArmor=false)=>page.evaluate(async({id,nativeArmor})=>{
   const recipe=gameRecipeOf(id),actor=buildBlank();actor.id='recipe-artisan';actor.name='Мастер мастерской';actor.hp=20;actor.cls='Жрец';actor.inventory=[];actor.equipment={};actor.toolProficiencies=[];actor.knownRecipes=[id];actor.craftingFacilities=craftRequirementsOf(recipe.raw).facilities;actor.slots={1:{cur:2,max:2}};
   const counts=new Map();for(const input of recipe.inputs){if(input.station)continue;const itemId=nativeArmor&&input.operation==='Dye'?'it_holy_shield_life':input.ids[0];counts.set(itemId,(counts.get(itemId)||0)+input.qty);}
   for(const itemId of recipe.toolIds){counts.set(itemId,1);const tool=itemProfile(itemOf(itemId)).tool;if(tool)actor.toolProficiencies.push(tool.prof);}
   for(const [itemId,qty] of counts)actor.inventory.push({id:'component-'+actor.inventory.length,itemId,qty});
   if(nativeArmor){const target=actor.inventory.find(e=>e.itemId==='it_holy_shield_life');target.notes='Щит наставника';target.charges=2;actor.equipment.OFF_HAND=target.id;}
   actor.activeFx=[{uid:'work-expiry',k:'test',id:'work-expiry',expiresAtRound:fxRound+11,fx:[{stat:'ac',mode:'add',value:1}]}];chars=[actor];activeCharId=actor.id;await recipeOpen(id,actor.id);return {name:recipe.name,before:JSON.stringify(actor.inventory),round:fxRound};
  },{id,nativeArmor});
  const first=await seed('cr_iron_ingot');await page.evaluate(()=>{sheetTab='inventory';switchTab('chars');renderChars();});await page.getByRole('button',{name:/^Инструменты кузнеца, количество/}).click();await page.locator('#tab-chars [onclick*="craftOpen("]').first().click();await page.locator('.recipe-card[data-recipe-id="cr_iron_ingot"]').waitFor();assert.equal(await page.locator('#recipeDuration').inputValue(),'240');
  await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).waitFor();assert.match(await page.locator('.recipe-confirm').innerText(),/Сохраняется: Инструменты кузнеца/);await page.locator('.recipe-confirm').getByRole('button',{name:'Отменить',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify(getCh('recipe-artisan').inventory)),first.before);
  await page.getByRole('button',{name:'Править запись',exact:true}).click();await page.locator('#recipeEditNote').fill('Кузница нашего мира');await page.locator('#recipeEditMinutes').fill('5');await page.getByRole('button',{name:'Сохранить рецепт',exact:true}).click();await page.getByRole('button',{name:'В избранное',exact:true}).click();
  await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).waitFor();await page.screenshot({path:path.join(output,'01-workshop-confirmation.png'),fullPage:true});
  await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).evaluate(button=>{button.click();button.click();});await page.waitForFunction(()=>getCh('recipe-artisan').craftingLog?.length===1);await page.locator('.recipe-history').waitFor();
  let result=await page.evaluate(()=>({qty:inventoryItemQty(getCh('recipe-artisan'),'it_mat_iron_ingot'),round:fxRound,fx:getCh('recipe-artisan').activeFx.length,log:getCh('recipe-artisan').craftingLog.length}));assert.deepEqual(result,{qty:1,round:first.round+50,fx:0,log:1});
  const potionId='bg3:recipe:ALCH_Potion_Healing_RoguesMorsel';await seed(potionId);await page.getByText('Любая суспензия',{exact:true}).first().waitFor();await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('alert').filter({hasText:/Мастер должен указать длительность/}).waitFor();assert.equal(await page.evaluate(()=>getCh('recipe-artisan').craftingLog?.length||0),0);
  await page.locator('#recipeDuration').fill('10');await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).waitFor();await page.locator('#recipeDuration').fill('12');assert.equal(await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).count(),0,'editing choices invalidates confirmation');await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).click();await page.locator('.recipe-history').waitFor();assert.equal(await page.evaluate(()=>getCh('recipe-artisan').craftingLog[0].minutes),12);
  const invisibilityId='bg3:recipe:ALCH_Potion_Invisibility_ImpPatagium',invisibility=await seed(invisibilityId);assert.match(await page.locator('[data-recipe-result-details]').innerText(),/1 час/);assert.equal(await page.locator('[data-recipe-result-details] .recipe-output-warning').count(),0);await page.getByLabel('Способ изготовления',{exact:true}).selectOption('cr_potion_invisibility');await page.waitForFunction(()=>document.querySelector('.recipe-card')?.dataset.recipeId==='cr_potion_invisibility');assert.match(await page.locator('[data-recipe-result-details]').innerText(),/1 час/);await page.getByLabel('Способ изготовления',{exact:true}).selectOption(invisibilityId);await page.locator('#recipeDuration').fill('2');await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).waitFor();assert.equal(await page.locator('.recipe-confirm .recipe-output-warning').count(),0);await page.locator('.recipe-confirm').getByRole('button',{name:'Отменить',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify(getCh('recipe-artisan').inventory)),invisibility.before);await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).click();await page.locator('.recipe-history').waitFor();assert.equal(await page.evaluate(()=>inventoryItemQty(getCh('recipe-artisan'),'it_potion_invisibility')),1);
  const featherfall=await seed('bg3:recipe:ALCH_Potion_FeatherFall_AutumnCrocus');assert.equal(await page.locator('[data-recipe-result-details] .recipe-output-warning').count(),0);await page.locator('#recipeDuration').fill('2');await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).waitFor();assert.equal(await page.locator('.recipe-confirm .recipe-output-warning').count(),0);await page.locator('.recipe-confirm').getByRole('button',{name:'Отменить',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify(getCh('recipe-artisan').inventory)),featherfall.before);
  const extraction=await seed('bg3:recipe:ALCH_Extract_ViridianCrystal');await page.evaluate(async()=>{await bg3CatalogHydrate(getCh('recipe-artisan').inventory.map(e=>e.itemId));sheetTab='inventory';switchTab('chars');renderChars();});await page.locator('#tab-chars .bag-slot-trigger').first().click();await page.locator('#tab-chars [onclick*="bg3RecipeProgramOpen("]').first().click();await page.locator('.recipe-card[data-recipe-id="bg3:recipe:ALCH_Extract_ViridianCrystal"]').waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(getCh('recipe-artisan').inventory)),extraction.before,'opening from an ingredient never crafts implicitly');
  const dyeId=await page.evaluate(()=>gameRecipeRows().find(r=>r.dye?.presetResource).id);await seed(dyeId,true);await page.locator('#recipeDuration').fill('2');await page.getByRole('button',{name:'Проверить изготовление',exact:true}).click();await page.getByRole('button',{name:'Подтвердить изготовление',exact:true}).click();await page.locator('.recipe-history').waitFor();const inventory=await page.evaluate(()=>getCh('recipe-artisan').inventory);assert.equal(inventory.length,1);assert.equal(inventory[0].notes,'Щит наставника');assert.equal(inventory[0].charges,2);assert.equal(inventory[0].bg3Dye.recipeId,dyeId);
  await page.evaluate(()=>runScheduledSave());await page.reload({waitUntil:'domcontentloaded'});await ready();assert.deepEqual(await page.evaluate(()=>getCh('recipe-artisan').inventory),inventory);assert.equal(await page.evaluate(()=>recipeState.overrides.cr_iron_ingot.note),'Кузница нашего мира');assert.equal(await page.evaluate(()=>recipeState.favorites.includes('cr_iron_ingot')),true);
  await page.locator('#itemsTabButton').click();await page.locator('#bg3ReleaseMetrics[data-catalog-state="ready"]').waitFor({timeout:120000});await page.getByRole('tab',{name:/^Рецепты/}).click();await page.locator('[data-game-recipes="193"]').waitFor();await page.locator('#bg3RuntimeSearch').fill('окрашивание');await page.waitForFunction(()=>bg3RuntimeQuery==='окрашивание'&&document.querySelector('.recipe-card h3')?.textContent.startsWith('Окрашивание:'));await page.setViewportSize({width:390,height:844});await page.locator('.recipe-card').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'02-workshop-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,'mobile page stays inside viewport');assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({ok:true,cards:193,methods:200,checks:['unified recipes','tool and ingredient actions open the same workshop','cancel without spending','retained tools preview','one commit on double click','world effects expire','required duration and category choice','form edits invalidate confirmation','alternative formulas create the same tabletop item','feather-fall result has complete usable mechanics','native armor coloring preserves instance','durable recipe edits and inventory','mobile layout'],errors},null,2));console.log('Recipe workshop browser journey passed.');
 }catch(error){if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw error;}finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
