'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright')));}
const root=path.resolve(__dirname,'..',process.env.QA_SITE_ROOT||'.'),out=path.resolve(process.env.QA_ARTIFACT_DIR||path.join(__dirname,'evidence','gm-reference'));fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/(?:dnd-world\/)?/,''),file=path.resolve(root,relative||'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404).end();return;}res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});let page;
 try{
  page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(45000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  const open=async()=>{await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'✠ Новый герой',exact:true}).or(page.getByRole('button',{name:'← К списку героев',exact:true})).first().waitFor({timeout:120000});await page.locator('.tab[data-tab="rules"]').click();};
  await open();const panel=page.locator('#tab-rules'),tabs=panel.getByRole('tab');assert.equal(await tabs.count(),8);
  const worldBefore=await page.evaluate(()=>JSON.stringify({chars,combat,rulesDB,campaignMagic}));
  assert.ok(await panel.getByRole('heading',{name:'Атака оружием',exact:true}).isVisible());
  for(const tab of await tabs.all()){await tab.click();assert.equal(await tab.getAttribute('aria-selected'),'true');assert.ok(await panel.locator('.gm-panel h3').isVisible());}
  await panel.getByRole('tab',{name:/^Формулы/}).click();await panel.screenshot({path:path.join(out,'desktop-formulas.png')});await panel.evaluate(e=>e.scrollIntoView());await page.screenshot({path:path.join(out,'desktop-viewport.png')});
  await panel.getByRole('tab',{name:/^Ход и бой/}).focus();await page.keyboard.press('ArrowRight');assert.equal(await panel.getByRole('tab',{name:/^Состояния/}).getAttribute('aria-selected'),'true');
  await page.keyboard.press('Home');assert.equal(await panel.getByRole('tab',{name:/^Формулы/}).getAttribute('aria-selected'),'true');
  await panel.getByLabel('Найти правило',{exact:true}).fill('концентрац');assert.ok(await panel.locator('.gm-card[data-entry="concentration-save"]').isVisible());assert.ok(await panel.locator('.gm-card[data-entry="concentration"]').isVisible());
  await panel.getByRole('button',{name:'В избранное: Спасбросок концентрации',exact:true}).click();await panel.getByRole('button',{name:'Сбросить',exact:true}).click();await panel.getByRole('button',{name:'★ Избранное',exact:true}).click();assert.equal(await panel.locator('.gm-card').count(),1);
  await panel.getByRole('button',{name:'Сбросить',exact:true}).click();await panel.getByLabel('Найти правило',{exact:true}).fill('неттакогоправила');assert.ok(await panel.getByRole('heading',{name:'Ничего не найдено'}).isVisible());await panel.getByRole('button',{name:'Сбросить поиск и фильтр'}).click();
  await panel.locator('.gm-calculator summary').click();await panel.getByLabel('Полученный урон',{exact:true}).fill('23');await panel.getByRole('button',{name:'Рассчитать',exact:true}).click();assert.match(await panel.locator('output').innerText(),/СЛ концентрации: 11/);
  await panel.getByLabel('Что рассчитать',{exact:true}).selectOption('damage');await panel.getByLabel('Урон одного типа',{exact:true}).fill('19');await panel.getByLabel('Результат спасброска').selectOption('half');await panel.getByLabel('Защита от этого типа').selectOption('resistance');await panel.getByLabel('Временные хиты',{exact:true}).fill('3');await panel.getByRole('button',{name:'Рассчитать',exact:true}).click();assert.match(await panel.locator('output').innerText(),/Полученный урон: 4\. Потеря обычных хитов: 1/);
  assert.equal(await page.evaluate(()=>JSON.stringify({chars,combat,rulesDB,campaignMagic})),worldBefore,'reading, favorites and calculators never change the world');
  await panel.getByRole('button',{name:'+ Запись мастера',exact:true}).first().click();await panel.getByLabel('Заголовок',{exact:true}).fill('Памятка испытания');await panel.getByLabel('Текст записи',{exact:true}).fill('Не потерять черновик <img src=x onerror=alert(1)>');
  await page.locator('.tab[data-tab="chars"]').click();await page.locator('.tab[data-tab="rules"]').click();assert.equal(await panel.getByLabel('Заголовок',{exact:true}).inputValue(),'Памятка испытания','leaving and reopening the reference preserves the unsaved note');
  await panel.getByRole('tab',{name:/^Ход и бой/}).click();await panel.getByLabel('Найти правило',{exact:true}).fill('урон');assert.equal(await panel.getByLabel('Заголовок',{exact:true}).inputValue(),'Памятка испытания','search and tabs preserve unsaved editor');
  await panel.getByRole('button',{name:'Вписать в свод'}).click();await panel.getByRole('tab',{name:/^Записи мастера/}).click();const note=panel.locator('.gm-card').filter({hasText:'Памятка испытания'});assert.equal(await note.locator('img').count(),0);assert.match(await note.innerText(),/<img/);
  await note.getByRole('button',{name:'Править',exact:true}).click();await panel.getByLabel('Текст записи',{exact:true}).fill('Проверить мост перед прыжком.');await panel.getByRole('button',{name:'Вписать в свод'}).click();
  await page.evaluate(async()=>{savePendWorld=true;if(!await runScheduledSave())throw new Error('Save failed');});await open();assert.equal(await panel.getByRole('tab',{name:/^Записи мастера/}).getAttribute('aria-selected'),'true');assert.match(await panel.locator('.gm-panel').innerText(),/Проверить мост/);
  await panel.getByRole('button',{name:'★ Избранное',exact:true}).click();assert.equal(await panel.locator('.gm-card').count(),1,'favorites survive reload');
  await panel.getByRole('tab',{name:/^Таблицы/}).click();assert.ok(await panel.getByRole('heading',{name:'Предыстории проекта',exact:true}).isVisible());assert.ok(await panel.getByRole('heading',{name:'Опыт и бонус мастерства',exact:true}).isVisible());
  await page.setViewportSize({width:390,height:844});for(const tab of await tabs.all()){await tab.click();assert.ok(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth+2),'reference fits on mobile');}await panel.getByRole('tab',{name:/^Состояния/}).click();await panel.screenshot({path:path.join(out,'mobile-conditions.png')});await panel.evaluate(e=>e.scrollIntoView());await page.screenshot({path:path.join(out,'mobile-viewport.png')});
  await page.setViewportSize({width:1440,height:1100});await panel.getByRole('tab',{name:/^Формулы/}).click();await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.ok(await panel.evaluate(e=>e.scrollWidth<=e.clientWidth+2),'reference supports enlarged text');await page.evaluate(()=>document.documentElement.style.fontSize='');
  await panel.getByRole('tab',{name:/^Записи мастера/}).click();await panel.locator('.gm-card').filter({hasText:'Памятка испытания'}).getByRole('button',{name:'Удалить',exact:true}).click();assert.equal(await panel.locator('.gm-card').filter({hasText:'Памятка испытания'}).count(),0);
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({ok:true,tabs:8,checks:['all tabs','keyboard navigation','cross-section search','favorites reload','manual calculations do not change combat','notes create/edit/delete/reload','HTML escaping','draft preservation','mobile overflow'],errors},null,2));console.log('GM reference passed desktop, mobile, search, favorites, calculations and note persistence checks.');
 }catch(error){if(page)await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw error;}finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
