'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright')));}
const root=path.resolve(__dirname,'..',process.env.QA_SITE_ROOT||'.'),output=process.env.QA_ARTIFACT_DIR?path.resolve(process.env.QA_ARTIFACT_DIR,'grimoire-workbench'):path.join(__dirname,'evidence','grimoire-workbench');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/dnd-world(?:\/|$)/,'/').replace(/^\//,'');const file=path.resolve(root,relative||'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404).end();return;}res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const baseUrl=process.env.QA_BASE_URL||'http://127.0.0.1:'+server.address().port,origin=new URL(baseUrl).origin,browser=await chromium.launch({headless:true});let page;
 try{
 page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());page.setDefaultTimeout(30000);
 // A fresh browser context and blocked external services isolate this fixture from saved campaigns.
 await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await page.goto(baseUrl,{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'✠ Новый герой',exact:true}).or(page.getByRole('button',{name:'← К списку героев',exact:true})).first().waitFor({timeout:120000});
 const release=await page.locator('meta[name="dnd-world-release"]').getAttribute('content');if(process.env.QA_EXPECTED_COMMIT)assert.equal(release,process.env.QA_EXPECTED_COMMIT,'the tested page must be the expected release');
 // Isolated campaign fixture. Every behavior below uses actual controls.
 await page.evaluate(()=>{
   const c=Object.assign(buildBlank(),{id:'desk-wizard',name:'Мастерская · волшебник',cls:'Волшебник',level:5}),d=Object.assign(buildBlank(),{id:'desk-druid',name:'Мастерская · друид',cls:'Друид',subcls:'Круг Земли',level:5});
   chars=[c,d];for(const actor of chars){characterAdopt(actor);applyClassSlots(actor);upgradeSpellcastingState(actor);}
   c.spellbook=[{spellId:'sp_magic_missile',access:'spellbook',prep:true}];activeCharId=c.id;sheetTab='spells';switchTab('spellsdb');renderSpellsDB();
 });
 const search=page.getByRole('searchbox',{name:'Поиск в гримуаре'}),hero=page.getByRole('combobox',{name:'Герой в гримуаре'});
 await hero.selectOption('desk-wizard');await search.pressSequentially('Magic Missile');assert.equal(await search.evaluate(el=>el===document.activeElement),true);
 let entry=page.locator('.grimoire-entry').first();await entry.locator('summary').click();assert.match(await entry.locator('.grimoire-status').innerText(),/Доступно по списку и ресурсу/);
 await entry.getByRole('button',{name:'☆ В избранное',exact:true}).click();assert.equal(await entry.getAttribute('open'),'');await entry.getByRole('button',{name:'Сравнить',exact:true}).click();
 await entry.getByRole('textbox',{name:/Заметка мастера/}).fill('Для сцены у ворот. <script>ошибка</script>');await search.click();
 await search.fill('Burning Hands');entry=page.locator('.grimoire-entry').first();await entry.locator('summary').click();assert.match(await entry.locator('.grimoire-status').innerText(),/Нужно изучить/);await entry.getByRole('button',{name:'Сравнить',exact:true}).click();
 assert.equal(await page.locator('.grimoire-compare-grid article').count(),2);await page.screenshot({path:path.join(output,'01-workbench-desktop.png'),fullPage:false});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'02-workbench-mobile.png'),fullPage:true});assert.equal(await page.locator('body').evaluate(el=>el.scrollWidth<=window.innerWidth),true);
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Сбросить фильтры',exact:true}).click();await page.getByRole('button',{name:'★ Избранное',exact:true}).click();assert.equal(await page.locator('.grimoire-entry').count(),1);
 await page.getByRole('button',{name:'★ Избранное',exact:true}).click();await search.fill('Magic Missile');entry=page.locator('.grimoire-entry').first();if(!await entry.getAttribute('open')&&await entry.getAttribute('open')!== '')await entry.locator('summary').click();
 await entry.getByRole('button',{name:'Наложить · Мастерская · волшебник',exact:true}).click();await page.locator('#castBack').waitFor({state:'visible'});await page.locator('#castStep1').getByRole('button',{name:'Отмена',exact:true}).click();assert.equal(await page.evaluate(()=>getCh('desk-wizard').slots[1].cur),4);
 // Character access and executable consequences are independent filters.
 const manual=await page.evaluate(()=>{const c=getCh('desk-wizard'),sp=spellsDB.find(sp=>grimoireActive(sp)&&sp.l>0&&sp.l<=3&&spellClassListHas(c,sp)&&!grimoireSpellStatus(c,sp).engineReady);c.spellbook.push({spellId:sp.id,access:'spellbook',prep:true});return {id:sp.id,name:sp.n};});
 await page.getByRole('combobox',{name:'Доступ героя',exact:true}).selectOption('ready');await search.fill(manual.name);entry=page.locator('.grimoire-entry').filter({has:page.locator('summary strong',{hasText:manual.name})}).first();await entry.locator('summary').click();assert.equal(await entry.getAttribute('data-spell-id'),manual.id);assert.equal(await entry.getByRole('button',{name:'Наложить · Мастерская · волшебник',exact:true}).isDisabled(),true);
 await page.getByRole('combobox',{name:'Свойства заклинания',exact:true}).selectOption('automatic');assert.equal(await page.locator('.grimoire-entry[data-spell-id="'+manual.id+'"]').count(),0);
 await page.getByRole('combobox',{name:'Порядок заклинаний',exact:true}).selectOption('name');await page.getByRole('button',{name:'Сбросить фильтры',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Доступ героя',exact:true}).inputValue(),'all');assert.equal(await page.getByRole('combobox',{name:'Порядок заклинаний',exact:true}).inputValue(),'level');assert.equal(await hero.inputValue(),'desk-wizard');
 // The two expended circles distinguish the player selection from the old greedy recovery.
 await page.evaluate(()=>{const c=getCh('desk-wizard');c.slots[1].cur=0;c.slots[3].cur=0;});
 await page.getByRole('button',{name:'Открыть магию героя',exact:true}).click();await page.getByRole('button',{name:'☕ Короткий отдых',exact:true}).first().click();
 const dialog=page.locator('#magic-recovery-dialog');await dialog.waitFor({state:'visible'});await page.evaluate(()=>{getCh('desk-wizard').level=6;});await dialog.getByRole('button',{name:'Завершить отдых и восстановить',exact:true}).click();assert.match(await dialog.getByRole('alert').innerText(),/изменилась/);assert.deepEqual(await page.evaluate(()=>[getCh('desk-wizard').slots[1].cur,getCh('desk-wizard').slots[3].cur,!!getCh('desk-wizard').arcUsed]),[0,0,false]);await dialog.getByRole('button',{name:'Отмена',exact:true}).click();await dialog.waitFor({state:'detached'});await page.evaluate(()=>{getCh('desk-wizard').level=5;});await page.getByRole('button',{name:'☕ Короткий отдых',exact:true}).first().click();await dialog.waitFor({state:'visible'});await dialog.getByRole('spinbutton',{name:'Восстановить ячейки 3 круга'}).fill('1');await dialog.getByRole('spinbutton',{name:'Восстановить ячейки 1 круга'}).fill('1');await dialog.getByRole('button',{name:'Завершить отдых и восстановить',exact:true}).click();assert.match(await dialog.getByRole('alert').innerText(),/превышает/);assert.deepEqual(await page.evaluate(()=>[getCh('desk-wizard').slots[1].cur,getCh('desk-wizard').slots[3].cur]),[0,0]);
 await dialog.getByRole('spinbutton',{name:'Восстановить ячейки 1 круга'}).fill('0');await page.screenshot({path:path.join(output,'03-recovery.png'),fullPage:false});await dialog.getByRole('button',{name:'Завершить отдых и восстановить',exact:true}).click();await dialog.waitFor({state:'detached'});assert.deepEqual(await page.evaluate(()=>[getCh('desk-wizard').slots[1].cur,getCh('desk-wizard').slots[3].cur,getCh('desk-wizard').arcUsed]),[0,1,true]);
 await page.locator('.tab[data-tab="spellsdb"]').click();await hero.selectOption('desk-druid');await page.locator('#tab-spellsdb .caster-guide summary').click();await page.getByRole('combobox',{name:'Местность Круга Земли'}).selectOption({label:'Побережье'});await search.fill('Misty Step');entry=page.locator('.grimoire-entry').first();await entry.locator('summary').click();assert.match(await entry.locator('.grimoire-status').innerText(),/Доступно по списку и ресурсу/);
 await page.evaluate(()=>runScheduledSave());await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'✠ Новый герой',exact:true}).or(page.getByRole('button',{name:'← К списку героев',exact:true})).first().waitFor({timeout:120000});
 await page.locator('.tab[data-tab="spellsdb"]').click();await search.fill('Magic Missile');await page.locator('.grimoire-entry summary').click();assert.equal(await page.getByRole('textbox',{name:/Заметка мастера/}).inputValue(),'Для сцены у ворот. <script>ошибка</script>');assert.equal(await page.locator('.grimoire-entry').getByRole('button',{name:'★ В избранном',exact:true}).count(),1);assert.equal(await page.evaluate(()=>getCh('desk-druid').circleLand),'Побережье');assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'browser-result.json'),JSON.stringify({ok:true,url:baseUrl,release,checks:['hero availability and class guidance','search retains focus','favorites','inert escaped notes persist','comparison of two spells','390px layout','real cast cancellation','manual spell access independent of automation; complete filter reset','recovery selection, cancellation, stale context and over-budget rejection','Land spells reach actual character and MP-compatible access','reload'],errors},null,2));console.log('Grimoire workbench browser journey passed.');
 }catch(error){if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw error;}finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
