'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright')));}
const root=path.resolve(__dirname,'..',process.env.QA_SITE_ROOT||'.'),output=path.resolve(process.env.QA_ARTIFACT_DIR||path.join(__dirname,'evidence','recipe-tabletop'),'browser');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const relative=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/(?:dnd-world\/)?/,''),file=path.resolve(root,relative||'index.html');if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.stat(file,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404).end();return;}res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});});
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,channel:process.env.QA_BROWSER_CHANNEL||undefined});let page;
 try{
  page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(45000);const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('dialog',d=>d.accept());await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  const ready=async()=>page.getByRole('button',{name:'✠ Новый герой',exact:true}).or(page.getByRole('button',{name:'← К списку героев',exact:true})).first().waitFor({timeout:120000});
  await page.goto(base,{waitUntil:'domcontentloaded'});await ready();
  // Provision a local acceptance world. Every action below uses rendered controls.
  await page.evaluate(()=>{const c=buildBlank(),t=buildBlank();c.id='native-crafter';c.name='Алхимик';c.inventory=[{id:'flash',itemId:DND_RECIPE_TABLETOP_ITEMS.byStats.OBJ_Bomb_Sunflash,qty:2},{id:'mucus',itemId:DND_RECIPE_TABLETOP_ITEMS.byStats.OBJ_CrawlerMucus,qty:2},{id:'dagger',itemId:'it_кинжал',qty:1}];c.equipment={};c.activeFx=[];t.id='native-target';t.name='Страж';t.activeFx=[];t.ab={str:10,dex:10,con:10,int:10,wis:10,cha:10};chars=[c,t];foesDB=[];combat=blankCombat();activeCharId=c.id;sheetTab='inventory';switchTab('chars');renderChars();});
  const openItem=async(name,action)=>{await page.getByRole('button',{name:new RegExp('^'+name+', количество')}).click();await page.locator('#tab-chars button[onclick*="itemCastFx("]').filter({hasText:action}).click();};
  await openItem('Слепящая вспышка','Бросить');await page.locator('#recipe-burst-dialog').waitFor();await page.locator('#recipe-burst-distance').fill('19');await page.getByRole('button',{name:'Применить ко всем целям',exact:true}).click();assert.match(await page.locator('#recipe-burst-error').innerText(),/точку|расстояние|существ/);assert.equal(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'flash').qty),2);
  await page.locator('#recipe-burst-distance').fill('3');await page.locator('[data-target="ally:native-target"]').check();await page.getByRole('button',{name:'Применить ко всем целям',exact:true}).click();assert.ok(await page.locator('#recipe-burst-error').innerText());assert.equal(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'flash').qty),2);
  await page.locator('[data-roll="1:recipe_burst_save"]').fill('1');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'01-burst-mobile.png')});assert.equal(await page.locator('#recipe-burst-dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+2),true,'mobile burst fits its dialog');await page.getByRole('button',{name:'Применить ко всем целям',exact:true}).click();await page.locator('#recipe-burst-dialog').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'flash').qty),1);assert.equal(await page.evaluate(()=>effectiveConditions(getCh('native-target')).includes('Ослепленный')),true);assert.equal(await page.evaluate(()=>effectiveConditions(getCh('native-crafter')).includes('Ослепленный')),false);
  await page.setViewportSize({width:1440,height:1100});await openItem('Слизь гусеницы','Нанести на отдельный предмет');await page.locator('#rs-item').selectOption('dagger');await page.getByRole('button',{name:'Нанести дозу',exact:true}).click();await page.locator('.recipe-dialog').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'mucus').qty),1);assert.ok(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'dagger').recipeContactPoison));
  await page.getByRole('button',{name:'Характеристики',exact:true}).click();await page.getByRole('button',{name:/^Контакт с ядом:/}).click();await page.locator('#rc-target').selectOption('ally:native-target');await page.screenshot({path:path.join(output,'02-contact-confirmation.png')});await page.locator('.recipe-dialog').getByRole('button',{name:'Отмена',exact:true}).click();assert.ok(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'dagger').recipeContactPoison));await page.getByRole('button',{name:'Смыть контактный яд',exact:true}).click();assert.equal(await page.evaluate(()=>!!invEntryOf(getCh('native-crafter'),'dagger').recipeContactPoison),false);
  await page.evaluate(()=>runScheduledSave());await page.reload({waitUntil:'domcontentloaded'});await ready();assert.equal(await page.evaluate(()=>invEntryOf(getCh('native-crafter'),'flash').qty),1);assert.equal(await page.evaluate(()=>effectiveConditions(getCh('native-target')).includes('Ослепленный')),true);assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({ok:true,checks:['native inventory actions','invalid area and absent dice never spend','individual target saves','one grenade consumed','mobile dialog','contact poison lives on one item','cancel keeps the dose','wash removes the dose','save and reload'],errors},null,2));console.log('Native tabletop browser journey passed.');
 }catch(error){if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});throw error;}finally{await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
