'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.resolve(path.dirname(process.execPath),'../node_modules/playwright')));}
const root=path.resolve(__dirname,'..'),output=path.join(__dirname,'evidence','merchant-chest');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'index.html');if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.stat(file,(err,stat)=>{if(err||!stat.isFile())return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.message);});page.on('dialog',d=>d.accept(d.type()==='prompt'?'Проверка мастера':undefined));page.setDefaultTimeout(30000);
// Boot the unmodified application before installing the small, isolated scenario world.
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await page.locator('#tab-merchants .trade-workspace').waitFor({state:'attached',timeout:120000});
await page.evaluate(()=>{racesDB=seedRacesDB();classesDB=seedClassesDB();itemsDB=seedItemsDB();const c=Object.assign(buildBlank(),{id:'qa-hero',name:'Элира',coins:{zm:100,mm:0,sm:0,em:0,pm:0},hp:20,hpMax:20});characterAdopt(c);chars=[c];itemsDB.push({id:'qa-rope',n:'Дорожная верёвка',type:'equipment',tags:['general-goods','rope'],rarity:'обычный',cost:'1 зм',custom:true});});
await page.locator('[data-tab="merchants"]').click();await page.locator('#merchantCreateName').fill('Бринн Меднобород');await page.locator('#merchantCreateRegion').fill('Северный рынок');await page.screenshot({path:path.join(output,'01-merchant-create.png'),fullPage:true});await page.locator('#merchantCreateButton').click();
await page.getByRole('button',{name:'Ассортимент',exact:true}).click();await page.getByRole('searchbox',{name:'Поиск предмета'}).fill('Дорожная верёвка');await page.locator('#merchantAddItem').selectOption('qa-rope');await page.getByRole('button',{name:'Добавить товар',exact:true}).click();
await page.getByRole('button',{name:'Торговля',exact:true}).click();await page.getByRole('searchbox',{name:'Поиск в ассортименте'}).fill('Дорожная');const product=page.locator('[data-merchant-item="qa-rope"]');await product.locator('input').fill('2');assert.match(await product.innerText(),/Итого 2 зм/);await product.getByRole('button',{name:'Купить',exact:true}).click();
assert.equal(await page.evaluate(()=>getCh('qa-hero').inventory.find(e=>e.itemId==='qa-rope').qty),2);assert.equal(await page.evaluate(()=>economyService().totalMinor(economyAccountFor(getCh('qa-hero')))),'9800');
const entryId=await page.evaluate(()=>getCh('qa-hero').inventory.find(e=>e.itemId==='qa-rope').id);await page.locator('#merchantSellItem').selectOption(entryId);assert.match(await page.locator('#merchantSellPreview').innerText(),/5 см/);await page.locator('#merchantSellButton').click();assert.equal(await page.evaluate(()=>economyService().totalMinor(economyAccountFor(getCh('qa-hero')))),'9850');
await page.screenshot({path:path.join(output,'02-merchant-trade.png'),fullPage:true});await page.getByRole('button',{name:'Настройки мастера',exact:true}).click();await page.locator('#merchantPurchaseMultiplier').fill('112.25');await page.locator('#merchantPurchaseMultiplier').dispatchEvent('change');assert.equal(await page.locator('#merchantPurchaseMultiplier').inputValue(),'112.25');
await page.locator('[data-tab="chests"]').click();await page.getByRole('button',{name:'+ Создать сундук',exact:true}).click();await page.getByRole('searchbox',{name:'Поиск предмета'}).first().fill('Дорожная верёвка');await page.locator('#chestAddItem').selectOption('qa-rope');await page.getByRole('button',{name:'Добавить предмет',exact:true}).click();await page.getByRole('spinbutton',{name:'Награда: золотые',exact:true}).fill('7');await page.getByRole('spinbutton',{name:'Награда: золотые',exact:true}).dispatchEvent('change');await page.getByRole('button',{name:'Утвердить содержимое',exact:true}).click();
await page.screenshot({path:path.join(output,'03-chest-loot.png'),fullPage:true});await page.getByRole('button',{name:'Свойства',exact:true}).click();await page.locator('[data-chest-field="lockType"]').selectOption('none');await page.getByRole('button',{name:'Игра',exact:true}).click();await page.getByRole('button',{name:'Разместить на сцене',exact:true}).click();await page.locator('.chest-player-action').filter({hasText:'Открыть'}).click();assert.equal(await page.evaluate(()=>chestOf(chestUiSelectedId).state),'opened');assert.equal(await page.evaluate(()=>chestOf(chestUiSelectedId).container.loot.status),'approved');await page.locator('.chest-player-action').filter({hasText:'Забрать добычу'}).click();assert.equal(await page.evaluate(()=>chestOf(chestUiSelectedId).container.loot.status),'claimed');assert.equal(await page.evaluate(()=>economyService().totalMinor(economyAccountFor(getCh('qa-hero')))),'10550');assert.equal(await page.locator('.chest-player-action').filter({hasText:'Забрать добычу'}).isDisabled(),true);
await page.screenshot({path:path.join(output,'04-chest-game.png'),fullPage:true});await page.getByRole('button',{name:'Содержимое',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Добавить предмет',exact:true}).count(),0);
for(const tab of ['chests','merchants']){await page.locator('[data-tab="'+tab+'"]').click();await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth<=window.innerWidth),true,'no mobile overflow '+tab);await page.screenshot({path:path.join(output,'05-mobile-'+tab+'.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});}
// Trap cancellation must leave actor, resources, loot and chest exactly intact.
await page.locator('[data-tab="chests"]').click();await page.locator('.chest-toolbar select').selectOption('trapped-vault');await page.getByRole('button',{name:'+ Создать сундук',exact:true}).click();await page.getByRole('button',{name:'Утвердить содержимое',exact:true}).click();await page.getByRole('button',{name:'Свойства',exact:true}).click();await page.locator('[data-chest-field="lockType"]').selectOption('none');await page.locator('[data-chest-field="saveAbility"]').selectOption('con');await page.locator('[data-chest-field="saveEffect"]').selectOption('none');await page.getByRole('button',{name:'Игра',exact:true}).click();await page.getByRole('button',{name:'Разместить на сцене',exact:true}).click();
const beforeCancel=await page.evaluate(()=>JSON.stringify({actor:getCh('qa-hero'),chest:chestOf(chestUiSelectedId),combat:{...combat,actionAudit:[]}}));await page.locator('.chest-player-action').filter({hasText:'Открыть'}).click();await page.locator('#rollBack').getByRole('button',{name:'Отмена',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.stringify({actor:getCh('qa-hero'),chest:chestOf(chestUiSelectedId),combat:{...combat,actionAudit:[]}})),beforeCancel);
await page.locator('.chest-player-action').filter({hasText:'Открыть'}).click();assert.match(await page.locator('#rollRows').innerText(),/Телосложения/);await page.locator('#rollRows input').nth(0).fill('20');await page.locator('#rollRows input').nth(1).fill('8');await page.getByRole('button',{name:'Рассчитать и применить',exact:true}).click();assert.equal(await page.evaluate(()=>getCh('qa-hero').hp),20);assert.equal(await page.evaluate(()=>chestOf(chestUiSelectedId).container.trap.triggered),true);
// Exercise table constraints through visible controls, retaining focus during edits.
await page.locator('.chest-toolbar select').selectOption('wooden-cache');await page.getByRole('button',{name:'+ Создать сундук',exact:true}).click();await page.getByText('Таблица добычи · весь каталог',{exact:true}).click();const table=page.locator('details').filter({has:page.locator('#chestTableItem')});await table.getByRole('searchbox').fill('Дорожная');await page.locator('#chestTableItem').selectOption('qa-rope');await table.getByRole('button',{name:'Добавить в таблицу',exact:true}).click();assert.match(await page.locator('.chest-table-row').innerText(),/100%/);await page.locator('.chest-table-row').getByRole('spinbutton',{name:'Уровень от',exact:true}).fill('10');await page.locator('.chest-table-row').getByRole('spinbutton',{name:'Уровень от',exact:true}).dispatchEvent('change');await page.locator('.chest-table-row').getByRole('spinbutton',{name:'Уровень до',exact:true}).fill('5');await page.locator('.chest-table-row').getByRole('spinbutton',{name:'Уровень до',exact:true}).dispatchEvent('change');assert.equal(await page.evaluate(()=>chestOf(chestUiSelectedId).container.lootTable[0].maxLevel),20);
await page.evaluate(async()=>{await rulesetLoadManifest();savePendWorld=true;await runScheduledSave();});const stored=await page.evaluate(async()=>({chests:await readJSON('dndworld2:chest-state'),merchants:await readJSON('dndworld2:merchant-state')}));assert.equal(stored.chests.instances[0].container.loot.status,'claimed');assert.equal(stored.merchants.instances[0].name,'Бринн Меднобород');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'browser-result.json'),JSON.stringify({ok:true,checks:['merchant creation preview','item search','live total','atomic purchase','sale pays 50 percent once','decimal price factor','manual loot and exact coins','approval','unlock and placement','open separately from claim','claim once','claimed loot read only','390px layouts','trap cancellation is non-mutating','Constitution save with no damage on success','loot table weights and level validation','campaign persistence','no page errors']},null,2));console.log('Treasure workspaces browser journey passed.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
